// Skins database with paint_index and buff163 ID mapping
// Extracted from CSGO-API and ModestSerhat/cs2-marketplace-ids
// Total unique skins: 1913

interface SkinData {
  paint_index: number;
  buff_id?: number;
}

export const skinDatabase: Record<string, SkinData> = {
  "AK-47 | Aphrodite": { paint_index: 1397 },
  "AK-47 | Aquamarine Revenge": { paint_index: 474 },
  "AK-47 | Asiimov": { paint_index: 801 },
  "AK-47 | B the Monster": { paint_index: 142 },
  "AK-47 | Baroque Purple": { paint_index: 745 },
  "AK-47 | Black Laminate": { paint_index: 172 },
  "AK-47 | Bloodsport": { paint_index: 639 },
  "AK-47 | Blue Laminate": { paint_index: 226 },
  "AK-47 | Breakthrough": { paint_index: 1358 },
  "AK-47 | Cartel": { paint_index: 394 },
  "AK-47 | Case Hardened": { paint_index: 44 },
  "AK-47 | Crane Flight": { paint_index: 1425 },
  "AK-47 | Crossfade": { paint_index: 912 },
  "AK-47 | Elite Build": { paint_index: 422 },
  "AK-47 | Emerald Pinstripe": { paint_index: 300 },
  "AK-47 | Fire Serpent": { paint_index: 180 },
  "AK-47 | First Class": { paint_index: 341 },
  "AK-47 | Frontside Misty": { paint_index: 490 },
  "AK-47 | Fuel Injector": { paint_index: 524 },
  "AK-47 | Gold Arabesque": { paint_index: 921 },
  "AK-47 | Green Laminate": { paint_index: 1070 },
  "AK-47 | Head Shot": { paint_index: 1221 },
  "AK-47 | Hydroponic": { paint_index: 456 },
  "AK-47 | Ice Coaled": { paint_index: 1143 },
  "AK-47 | Inheritance": { paint_index: 1171 },
  "AK-47 | Jaguar": { paint_index: 316 },
  "AK-47 | Jet Set": { paint_index: 340 },
  "AK-47 | Jungle Spray": { paint_index: 122 },
  "AK-47 | Leet Museo": { paint_index: 1087 },
  "AK-47 | Legion of Anubis": { paint_index: 959 },
  "AK-47 | Midnight Laminate": { paint_index: 1218 },
  "AK-47 | Neon Revolution": { paint_index: 600 },
  "AK-47 | Neon Rider": { paint_index: 707 },
  "AK-47 | Nightwish": { paint_index: 1141 },
  "AK-47 | Nouveau Rouge": { paint_index: 1309 },
  "AK-47 | Olive Polycam": { paint_index: 1179 },
  "AK-47 | Orbit Mk01": { paint_index: 656 },
  "AK-47 | Panthera onca": { paint_index: 1018 },
  "AK-47 | Phantom Disruptor": { paint_index: 941 },
  "AK-47 | Point Disarray": { paint_index: 506 },
  "AK-47 | Predator": { paint_index: 170 },
  "AK-47 | Rat Rod": { paint_index: 885 },
  "AK-47 | Red Laminate": { paint_index: 14 },
  "AK-47 | Redline": { paint_index: 282 },
  "AK-47 | Safari Mesh": { paint_index: 72 },
  "AK-47 | Safety Net": { paint_index: 795 },
  "AK-47 | Searing Rage": { paint_index: 1207 },
  "AK-47 | Slate": { paint_index: 1035 },
  "AK-47 | Steel Delta": { paint_index: 1238 },
  "AK-47 | The Empress": { paint_index: 675 },
  "AK-47 | The Oligarch": { paint_index: 1352 },
  "AK-47 | The Outsiders": { paint_index: 113 },
  "AK-47 | Uncharted": { paint_index: 836 },
  "AK-47 | VariCamo Grey": { paint_index: 1288 },
  "AK-47 | Vulcan": { paint_index: 302 },
  "AK-47 | Wasteland Rebel": { paint_index: 380 },
  "AK-47 | Wild Lotus": { paint_index: 724 },
  "AK-47 | Wintergreen": { paint_index: 1283 },
  "AK-47 | X-Ray": { paint_index: 1004 },
  "AUG | Akihabara Accept": { paint_index: 455 },
  "AUG | Amber Fade": { paint_index: 246 },
  "AUG | Amber Slipstream": { paint_index: 708 },
  "AUG | Anodized Navy": { paint_index: 197 },
  "AUG | Arctic Wolf": { paint_index: 886 },
  "AUG | Aristocrat": { paint_index: 583 },
  "AUG | Bengal Tiger": { paint_index: 9 },
  "AUG | Carved Jade": { paint_index: 1033 },
  "AUG | Chameleon": { paint_index: 280 },
  "AUG | Colony": { paint_index: 47 },
  "AUG | Commando Company": { paint_index: 1308 },
  "AUG | Condemned": { paint_index: 110 },
  "AUG | Contractor": { paint_index: 46 },
  "AUG | Copperhead": { paint_index: 10 },
  "AUG | Creep": { paint_index: 1362 },
  "AUG | Daedalus": { paint_index: 444 },
  "AUG | Death by Puppy": { paint_index: 913 },
  "AUG | Eye of Zapems": { paint_index: 134 },
  "AUG | Flame Jörmungandr": { paint_index: 758 },
  "AUG | Fleet Flock": { paint_index: 541 },
  "AUG | Hot Rod": { paint_index: 33 },
  "AUG | Lil' Pig": { paint_index: 173 },
  "AUG | Luxe Trim": { paint_index: 121 },
  "AUG | Midnight Lily": { paint_index: 727 },
  "AUG | Momentum": { paint_index: 845 },
  "AUG | Navy Murano": { paint_index: 740 },
  "AUG | Plague": { paint_index: 1088 },
  "AUG | Radiation Hazard": { paint_index: 375 },
  "AUG | Random Access": { paint_index: 779 },
  "AUG | Ricochet": { paint_index: 507 },
  "AUG | Sand Storm": { paint_index: 823 },
  "AUG | Snake Pit": { paint_index: 1249 },
  "AUG | Spalted Wood": { paint_index: 927 },
  "AUG | Steel Sentinel": { paint_index: 1198 },
  "AUG | Storm": { paint_index: 100 },
  "AUG | Stymphalian": { paint_index: 690 },
  "AUG | Surveillance": { paint_index: 995 },
  "AUG | Sweeper": { paint_index: 794 },
  "AUG | Syd Mead": { paint_index: 601 },
  "AUG | Tom Cat": { paint_index: 942 },
  "AUG | Torque": { paint_index: 305 },
  "AUG | Trigger Discipline": { paint_index: 1339 },
  "AUG | Triqua": { paint_index: 674 },
  "AUG | Wings": { paint_index: 73 },
  "AWP | Acheron": { paint_index: 788 },
  "AWP | Arsenic Spill": { paint_index: 1324 },
  "AWP | Asiimov": { paint_index: 279 },
  "AWP | Atheris": { paint_index: 838 },
  "AWP | BOOM": { paint_index: 174 },
  "AWP | Black Nile": { paint_index: 1239 },
  "AWP | CMYK": { paint_index: 163 },
  "AWP | Capillary": { paint_index: 943 },
  "AWP | Chromatic Aberration": { paint_index: 1144 },
  "AWP | Chrome Cannon": { paint_index: 1170 },
  "AWP | Containment Breach": { paint_index: 887 },
  "AWP | Corticera": { paint_index: 181 },
  "AWP | Crakow!": { paint_index: 137 },
  "AWP | Desert Hydra": { paint_index: 819 },
  "AWP | Dragon Lore": { paint_index: 344 },
  "AWP | Duality": { paint_index: 1222 },
  "AWP | Electric Hive": { paint_index: 227 },
  "AWP | Elite Build": { paint_index: 525 },
  "AWP | Exoskeleton": { paint_index: 975 },
  "AWP | Exothermic": { paint_index: 1378 },
  "AWP | Fade": { paint_index: 1026 },
  "AWP | Fever Dream": { paint_index: 640 },
  "AWP | Graphite": { paint_index: 212 },
  "AWP | Green Energy": { paint_index: 1280 },
  "AWP | Gungnir": { paint_index: 756 },
  "AWP | Hyper Beast": { paint_index: 475 },
  "AWP | Ice Coaled": { paint_index: 1346 },
  "AWP | Lightning Strike": { paint_index: 51 },
  "AWP | LongDog": { paint_index: 1213 },
  "AWP | Man-o'-war": { paint_index: 395 },
  "AWP | Medusa": { paint_index: 446 },
  "AWP | Mortis": { paint_index: 691 },
  "AWP | Neo-Noir": { paint_index: 803 },
  "AWP | Oni Taiji": { paint_index: 662 },
  "AWP | PAW": { paint_index: 718 },
  "AWP | POP AWP": { paint_index: 1058 },
  "AWP | Phobos": { paint_index: 584 },
  "AWP | Pink DDPAT": { paint_index: 84 },
  "AWP | Pit Viper": { paint_index: 251 },
  "AWP | Printstream": { paint_index: 1206 },
  "AWP | Queen's Gambit": { paint_index: 1422 },
  "AWP | Redline": { paint_index: 259 },
  "AWP | Safari Mesh": { paint_index: 72 },
  "AWP | Silk Tiger": { paint_index: 1029 },
  "AWP | Snake Camo": { paint_index: 30 },
  "AWP | Sun in Leo": { paint_index: 451 },
  "AWP | The End": { paint_index: 1356 },
  "AWP | The Prince": { paint_index: 736 },
  "AWP | Wildfire": { paint_index: 917 },
  "AWP | Worm God": { paint_index: 424 },
  "CZ75-Auto | Army Sheen": { paint_index: 298 },
  "CZ75-Auto | Chalice": { paint_index: 325 },
  "CZ75-Auto | Circaetus": { paint_index: 1036 },
  "CZ75-Auto | Copper Fiber": { paint_index: 1195 },
  "CZ75-Auto | Crimson Web": { paint_index: 12 },
  "CZ75-Auto | Distressed": { paint_index: 944 },
  "CZ75-Auto | Eco": { paint_index: 709 },
  "CZ75-Auto | Emerald": { paint_index: 453 },
  "CZ75-Auto | Emerald Quartz": { paint_index: 859 },
  "CZ75-Auto | Framework": { paint_index: 1076 },
  "CZ75-Auto | Green Plaid": { paint_index: 366 },
  "CZ75-Auto | Hexane": { paint_index: 218 },
  "CZ75-Auto | Honey Paisley": { paint_index: 1390 },
  "CZ75-Auto | Imprint": { paint_index: 602 },
  "CZ75-Auto | Indigo": { paint_index: 333 },
  "CZ75-Auto | Jungle Dashed": { paint_index: 147 },
  "CZ75-Auto | Midnight Palm": { paint_index: 933 },
  "CZ75-Auto | Nitro": { paint_index: 322 },
  "CZ75-Auto | Pink Pearl": { paint_index: 1329 },
  "CZ75-Auto | Poison Dart": { paint_index: 315 },
  "CZ75-Auto | Pole Position": { paint_index: 435 },
  "CZ75-Auto | Polymer": { paint_index: 622 },
  "CZ75-Auto | Red Astor": { paint_index: 543 },
  "CZ75-Auto | Silver": { paint_index: 32 },
  "CZ75-Auto | Slalom": { paint_index: 937 },
  "CZ75-Auto | Syndicate": { paint_index: 1064 },
  "CZ75-Auto | Tacticat": { paint_index: 687 },
  "CZ75-Auto | The Fuschia Is Now": { paint_index: 269 },
  "CZ75-Auto | Tigris": { paint_index: 350 },
  "CZ75-Auto | Tread Plate": { paint_index: 268 },
  "CZ75-Auto | Tuxedo": { paint_index: 297 },
  "CZ75-Auto | Twist": { paint_index: 334 },
  "CZ75-Auto | Vendetta": { paint_index: 976 },
  "CZ75-Auto | Victoria": { paint_index: 270 },
  "CZ75-Auto | Xiangliu": { paint_index: 643 },
  "CZ75-Auto | Yellow Jacket": { paint_index: 476 },
  "Desert Eagle | Blaze": { paint_index: 37 },
  "Desert Eagle | Blue Ply": { paint_index: 945 },
  "Desert Eagle | Bronze Deco": { paint_index: 425 },
  "Desert Eagle | Calligraffiti": { paint_index: 114 },
  "Desert Eagle | Cobalt Disruption": { paint_index: 231 },
  "Desert Eagle | Code Red": { paint_index: 711 },
  "Desert Eagle | Conspiracy": { paint_index: 351 },
  "Desert Eagle | Corinthian": { paint_index: 509 },
  "Desert Eagle | Crimson Web": { paint_index: 232 },
  "Desert Eagle | Directive": { paint_index: 603 },
  "Desert Eagle | Emerald Jörmungandr": { paint_index: 757 },
  "Desert Eagle | Fennec Fox": { paint_index: 764 },
  "Desert Eagle | Firebreathing": { paint_index: 1430 },
  "Desert Eagle | Golden Koi": { paint_index: 185 },
  "Desert Eagle | Hand Cannon": { paint_index: 328 },
  "Desert Eagle | Heat Treated": { paint_index: 1054 },
  "Desert Eagle | Heirloom": { paint_index: 273 },
  "Desert Eagle | Hypnotic": { paint_index: 61 },
  "Desert Eagle | Kumicho Dragon": { paint_index: 527 },
  "Desert Eagle | Light Rail": { paint_index: 841 },
  "Desert Eagle | Mecha Industries": { paint_index: 805 },
  "Desert Eagle | Meteorite": { paint_index: 296 },
  "Desert Eagle | Midnight Storm": { paint_index: 468 },
  "Desert Eagle | Mint Fan": { paint_index: 1257 },
  "Desert Eagle | Mudder": { paint_index: 90 },
  "Desert Eagle | Mulberry": { paint_index: 1318 },
  "Desert Eagle | Naga": { paint_index: 397 },
  "Desert Eagle | Night": { paint_index: 40 },
  "Desert Eagle | Night Heist": { paint_index: 1006 },
  "Desert Eagle | Ocean Drive": { paint_index: 1090 },
  "Desert Eagle | Oxide Blaze": { paint_index: 645 },
  "Desert Eagle | Pilot": { paint_index: 347 },
  "Desert Eagle | Printstream": { paint_index: 962 },
  "Desert Eagle | Serpent Strike": { paint_index: 1189 },
  "Desert Eagle | Sputnik": { paint_index: 1056 },
  "Desert Eagle | Starcade": { paint_index: 938 },
  "Desert Eagle | Sunset Storm 壱": { paint_index: 469 },
  "Desert Eagle | Sunset Storm 弐": { paint_index: 470 },
  "Desert Eagle | The Bronze": { paint_index: 992 },
  "Desert Eagle | The Daily Deagle": { paint_index: 1360 },
  "Desert Eagle | Tilted": { paint_index: 138 },
  "Desert Eagle | Trigger Discipline": { paint_index: 1050 },
  "Desert Eagle | Urban DDPAT": { paint_index: 17 },
  "Desert Eagle | Urban Rubble": { paint_index: 237 },
  "Dual Berettas | Angel Eyes": { paint_index: 1347 },
  "Dual Berettas | Anodized Navy": { paint_index: 28 },
  "Dual Berettas | Balance": { paint_index: 895 },
  "Dual Berettas | Black Limba": { paint_index: 190 },
  "Dual Berettas | BorDeux": { paint_index: 1335 },
  "Dual Berettas | Briar": { paint_index: 330 },
  "Dual Berettas | Cartel": { paint_index: 528 },
  "Dual Berettas | Cobalt Quartz": { paint_index: 249 },
  "Dual Berettas | Cobra Strike": { paint_index: 658 },
  "Dual Berettas | Colony": { paint_index: 47 },
  "Dual Berettas | Contractor": { paint_index: 46 },
  "Dual Berettas | Demolition": { paint_index: 153 },
  "Dual Berettas | Dezastre": { paint_index: 978 },
  "Dual Berettas | Drift Wood": { paint_index: 824 },
  "Dual Berettas | Dualing Dragons": { paint_index: 491 },
  "Dual Berettas | Duelist": { paint_index: 447 },
  "Dual Berettas | Elite 1.6": { paint_index: 903 },
  "Dual Berettas | Emerald": { paint_index: 453 },
  "Dual Berettas | Flora Carnivora": { paint_index: 1156 },
  "Dual Berettas | Heist": { paint_index: 1005 },
  "Dual Berettas | Hemoglobin": { paint_index: 220 },
  "Dual Berettas | Hideout": { paint_index: 1169 },
  "Dual Berettas | Hydro Strike": { paint_index: 112 },
  "Dual Berettas | Marina": { paint_index: 261 },
  "Dual Berettas | Melondrama": { paint_index: 1126 },
  "Dual Berettas | Moon in Libra": { paint_index: 450 },
  "Dual Berettas | Oil Change": { paint_index: 1086 },
  "Dual Berettas | Panther": { paint_index: 276 },
  "Dual Berettas | Polished Malachite": { paint_index: 1290 },
  "Dual Berettas | Pyre": { paint_index: 860 },
  "Dual Berettas | Retribution": { paint_index: 307 },
  "Dual Berettas | Rose Nacre": { paint_index: 1263 },
  "Dual Berettas | Royal Consorts": { paint_index: 625 },
  "Dual Berettas | Shred": { paint_index: 710 },
  "Dual Berettas | Silver Pour": { paint_index: 1373 },
  "Dual Berettas | Stained": { paint_index: 43 },
  "Dual Berettas | Sweet Little Angels": { paint_index: 139 },
  "Dual Berettas | Switch Board": { paint_index: 998 },
  "Dual Berettas | Tread": { paint_index: 1091 },
  "Dual Berettas | Twin Turbo": { paint_index: 747 },
  "Dual Berettas | Urban Shock": { paint_index: 396 },
  "Dual Berettas | Ventilators": { paint_index: 544 },
  "FAMAS | 2A2F": { paint_index: 1202 },
  "FAMAS | Afterimage": { paint_index: 154 },
  "FAMAS | Bad Trip": { paint_index: 1184 },
  "FAMAS | Byproduct": { paint_index: 1393 },
  "FAMAS | CaliCamo": { paint_index: 240 },
  "FAMAS | Colony": { paint_index: 47 },
  "FAMAS | Commemoration": { paint_index: 919 },
  "FAMAS | Contrast Spray": { paint_index: 22 },
  "FAMAS | Crypsis": { paint_index: 835 },
  "FAMAS | Cyanospatter": { paint_index: 92 },
  "FAMAS | Dark Water": { paint_index: 60 },
  "FAMAS | Decommissioned": { paint_index: 904 },
  "FAMAS | Djinn": { paint_index: 429 },
  "FAMAS | Doomkitty": { paint_index: 178 },
  "FAMAS | Eye of Athena": { paint_index: 723 },
  "FAMAS | Faulty Wiring": { paint_index: 1066 },
  "FAMAS | Grey Ghost": { paint_index: 1321 },
  "FAMAS | Half Sleeve": { paint_index: 461 },
  "FAMAS | Halftone Wash": { paint_index: 882 },
  "FAMAS | Hexane": { paint_index: 218 },
  "FAMAS | Macabre": { paint_index: 659 },
  "FAMAS | Mecha Industries": { paint_index: 626 },
  "FAMAS | Meltdown": { paint_index: 1053 },
  "FAMAS | Meow 36": { paint_index: 1146 },
  "FAMAS | Neural Net": { paint_index: 477 },
  "FAMAS | Night Borre": { paint_index: 863 },
  "FAMAS | Palm": { paint_index: 1302 },
  "FAMAS | Prime Conspiracy": { paint_index: 999 },
  "FAMAS | Pulse": { paint_index: 260 },
  "FAMAS | Rapid Eye Movement": { paint_index: 1127 },
  "FAMAS | Roll Cage": { paint_index: 604 },
  "FAMAS | Sergeant": { paint_index: 288 },
  "FAMAS | Spitfire": { paint_index: 194 },
  "FAMAS | Styx": { paint_index: 371 },
  "FAMAS | Sundown": { paint_index: 869 },
  "FAMAS | Survivor Z": { paint_index: 492 },
  "FAMAS | Teardown": { paint_index: 244 },
  "FAMAS | Valence": { paint_index: 529 },
  "FAMAS | Vendetta": { paint_index: 1365 },
  "FAMAS | Waters of Nephthys": { paint_index: 1241 },
  "FAMAS | Yeti Camo": { paint_index: 1219 },
  "FAMAS | ZX Spectron": { paint_index: 1092 },
  "Five-SeveN | Angry Mob": { paint_index: 837 },
  "Five-SeveN | Anodized Gunmetal": { paint_index: 210 },
  "Five-SeveN | Autumn Thicket": { paint_index: 1336 },
  "Five-SeveN | Berries And Cherries": { paint_index: 1002 },
  "Five-SeveN | Boost Protocol": { paint_index: 1093 },
  "Five-SeveN | Buddy": { paint_index: 906 },
  "Five-SeveN | Candy Apple": { paint_index: 3 },
  "Five-SeveN | Capillary": { paint_index: 646 },
  "Five-SeveN | Case Hardened": { paint_index: 44 },
  "Five-SeveN | Contractor": { paint_index: 46 },
  "Five-SeveN | Coolant": { paint_index: 784 },
  "Five-SeveN | Copper Galaxy": { paint_index: 274 },
  "Five-SeveN | Crimson Blossom": { paint_index: 729 },
  "Five-SeveN | Dark Polymer": { paint_index: 1429 },
  "Five-SeveN | Fairy Tale": { paint_index: 979 },
  "Five-SeveN | Fall Hazard": { paint_index: 1082 },
  "Five-SeveN | Flame Test": { paint_index: 693 },
  "Five-SeveN | Forest Night": { paint_index: 78 },
  "Five-SeveN | Fowl Play": { paint_index: 352 },
  "Five-SeveN | Fraise Crane": { paint_index: 1380 },
  "Five-SeveN | Heat Treated": { paint_index: 831 },
  "Five-SeveN | Hot Shot": { paint_index: 377 },
  "Five-SeveN | Hybrid": { paint_index: 1168 },
  "Five-SeveN | Hyper Beast": { paint_index: 660 },
  "Five-SeveN | Jungle": { paint_index: 151 },
  "Five-SeveN | Kami": { paint_index: 265 },
  "Five-SeveN | Midnight Paintover": { paint_index: 1062 },
  "Five-SeveN | Monkey Business": { paint_index: 427 },
  "Five-SeveN | Neon Kimono": { paint_index: 464 },
  "Five-SeveN | Nightshade": { paint_index: 223 },
  "Five-SeveN | Nitro": { paint_index: 254 },
  "Five-SeveN | Orange Peel": { paint_index: 141 },
  "Five-SeveN | Retrobution": { paint_index: 510 },
  "Five-SeveN | Scrawl": { paint_index: 1128 },
  "Five-SeveN | Scumbria": { paint_index: 605 },
  "Five-SeveN | Silver Quartz": { paint_index: 252 },
  "Five-SeveN | Sky Blue": { paint_index: 1262 },
  "Five-SeveN | Triumvirate": { paint_index: 530 },
  "Five-SeveN | Urban Hazard": { paint_index: 387 },
  "Five-SeveN | Violent Daimyo": { paint_index: 585 },
  "Five-SeveN | Withered Vine": { paint_index: 932 },
  "G3SG1 | Ancient Ritual": { paint_index: 1034 },
  "G3SG1 | Arctic Camo": { paint_index: 6 },
  "G3SG1 | Azure Zebra": { paint_index: 229 },
  "G3SG1 | Black Sand": { paint_index: 891 },
  "G3SG1 | Chronos": { paint_index: 438 },
  "G3SG1 | Contractor": { paint_index: 46 },
  "G3SG1 | Demeter": { paint_index: 195 },
  "G3SG1 | Desert Storm": { paint_index: 8 },
  "G3SG1 | Digital Mesh": { paint_index: 980 },
  "G3SG1 | Dream Glade": { paint_index: 1129 },
  "G3SG1 | Flux": { paint_index: 493 },
  "G3SG1 | Green Apple": { paint_index: 294 },
  "G3SG1 | Green Cell": { paint_index: 1305 },
  "G3SG1 | High Seas": { paint_index: 712 },
  "G3SG1 | Hunter": { paint_index: 677 },
  "G3SG1 | Jungle Dashed": { paint_index: 147 },
  "G3SG1 | Keeping Tabs": { paint_index: 1095 },
  "G3SG1 | Murky": { paint_index: 382 },
  "G3SG1 | New Roots": { paint_index: 930 },
  "G3SG1 | Orange Crash": { paint_index: 545 },
  "G3SG1 | Orange Kimono": { paint_index: 465 },
  "G3SG1 | Polar Camo": { paint_index: 74 },
  "G3SG1 | Red Jasper": { paint_index: 1328 },
  "G3SG1 | Safari Mesh": { paint_index: 72 },
  "G3SG1 | Scavenger": { paint_index: 806 },
  "G3SG1 | Stinger": { paint_index: 628 },
  "G3SG1 | The Executioner": { paint_index: 511 },
  "G3SG1 | VariCamo": { paint_index: 235 },
  "G3SG1 | Ventilator": { paint_index: 606 },
  "G3SG1 | Violet Murano": { paint_index: 739 },
  "Galil AR | Acid Dart": { paint_index: 1296 },
  "Galil AR | Akoben": { paint_index: 842 },
  "Galil AR | Amber Fade": { paint_index: 246 },
  "Galil AR | Aqua Terrace": { paint_index: 460 },
  "Galil AR | Black Sand": { paint_index: 629 },
  "Galil AR | Blue Titanium": { paint_index: 216 },
  "Galil AR | CAUTION!": { paint_index: 1071 },
  "Galil AR | Cerberus": { paint_index: 379 },
  "Galil AR | Chatterbox": { paint_index: 398 },
  "Galil AR | Chromatic Aberration": { paint_index: 1038 },
  "Galil AR | Cold Fusion": { paint_index: 790 },
  "Galil AR | Connexion": { paint_index: 972 },
  "Galil AR | Control": { paint_index: 1185 },
  "Galil AR | Crimson Tsunami": { paint_index: 647 },
  "Galil AR | Destroyer": { paint_index: 1147 },
  "Galil AR | Dusk Ruins": { paint_index: 1032 },
  "Galil AR | Eco": { paint_index: 428 },
  "Galil AR | Firefight": { paint_index: 546 },
  "Galil AR | Galigator": { paint_index: 1434 },
  "Galil AR | Green Apple": { paint_index: 294 },
  "Galil AR | Grey Smoke": { paint_index: 1275 },
  "Galil AR | Hunting Blind": { paint_index: 241 },
  "Galil AR | Kami": { paint_index: 308 },
  "Galil AR | Metallic Squeezer": { paint_index: 239 },
  "Galil AR | NV": { paint_index: 939 },
  "Galil AR | O-Ranger": { paint_index: 1314 },
  "Galil AR | Orange DDPAT": { paint_index: 83 },
  "Galil AR | Phoenix Blacklight": { paint_index: 1013 },
  "Galil AR | Rainbow Spoon": { paint_index: 1178 },
  "Galil AR | Robin's Egg": { paint_index: 1264 },
  "Galil AR | Rocket Pop": { paint_index: 478 },
  "Galil AR | Sage Spray": { paint_index: 119 },
  "Galil AR | Sandstorm": { paint_index: 264 },
  "Galil AR | Shattered": { paint_index: 192 },
  "Galil AR | Signal": { paint_index: 807 },
  "Galil AR | Sky Mandala": { paint_index: 1383 },
  "Galil AR | Stone Cold": { paint_index: 494 },
  "Galil AR | Sugar Rush": { paint_index: 661 },
  "Galil AR | Tornado": { paint_index: 101 },
  "Galil AR | Tuxedo": { paint_index: 297 },
  "Galil AR | Urban Rubble": { paint_index: 237 },
  "Galil AR | Vandal": { paint_index: 981 },
  "Galil AR | VariCamo": { paint_index: 235 },
  "Galil AR | Winter Forest": { paint_index: 76 },
  "Glock-18 | AXIA": { paint_index: 832 },
  "Glock-18 | Block-18": { paint_index: 1167 },
  "Glock-18 | Blue Fissure": { paint_index: 278 },
  "Glock-18 | Brass": { paint_index: 159 },
  "Glock-18 | Bullet Queen": { paint_index: 957 },
  "Glock-18 | Bunsen Burner": { paint_index: 479 },
  "Glock-18 | Candy Apple": { paint_index: 3 },
  "Glock-18 | Catacombs": { paint_index: 399 },
  "Glock-18 | Clear Polymer": { paint_index: 1039 },
  "Glock-18 | Coral Bloom": { paint_index: 1312 },
  "Glock-18 | Death Rattle": { paint_index: 293 },
  "Glock-18 | Dragon Tattoo": { paint_index: 48 },
  "Glock-18 | Fade": { paint_index: 38 },
  "Glock-18 | Franklin": { paint_index: 1016 },
  "Glock-18 | Fully Tuned": { paint_index: 1421 },
  "Glock-18 | Gamma Doppler": { paint_index: 1119 },
  "Glock-18 | Glockingbird": { paint_index: 1282 },
  "Glock-18 | Gold Toof": { paint_index: 129 },
  "Glock-18 | Green Line": { paint_index: 1200 },
  "Glock-18 | Grinder": { paint_index: 381 },
  "Glock-18 | Groundwater": { paint_index: 2 },
  "Glock-18 | High Beam": { paint_index: 799 },
  "Glock-18 | Ironwork": { paint_index: 623 },
  "Glock-18 | Mirror Mosaic": { paint_index: 1348 },
  "Glock-18 | Moonrise": { paint_index: 694 },
  "Glock-18 | Neo-Noir": { paint_index: 988 },
  "Glock-18 | Night": { paint_index: 40 },
  "Glock-18 | Nuclear Garden": { paint_index: 789 },
  "Glock-18 | Ocean Topo": { paint_index: 1265 },
  "Glock-18 | Off World": { paint_index: 680 },
  "Glock-18 | Oxide Blaze": { paint_index: 808 },
  "Glock-18 | Pink DDPAT": { paint_index: 84 },
  "Glock-18 | Ramese's Reach": { paint_index: 1240 },
  "Glock-18 | Reactor": { paint_index: 367 },
  "Glock-18 | Red Tire": { paint_index: 1079 },
  "Glock-18 | Royal Legion": { paint_index: 532 },
  "Glock-18 | Sacrifice": { paint_index: 918 },
  "Glock-18 | Sand Dune": { paint_index: 208 },
  "Glock-18 | Shinobu": { paint_index: 1208 },
  "Glock-18 | Snack Attack": { paint_index: 1100 },
  "Glock-18 | Steel Disruption": { paint_index: 230 },
  "Glock-18 | Synth Leaf": { paint_index: 732 },
  "Glock-18 | Teal Graf": { paint_index: 152 },
  "Glock-18 | Trace Lock": { paint_index: 1357 },
  "Glock-18 | Twilight Galaxy": { paint_index: 437 },
  "Glock-18 | Umbral Rabbit": { paint_index: 1227 },
  "Glock-18 | Vogue": { paint_index: 963 },
  "Glock-18 | Warhawk": { paint_index: 713 },
  "Glock-18 | Wasteland Rebel": { paint_index: 586 },
  "Glock-18 | Water Elemental": { paint_index: 353 },
  "Glock-18 | Weasel": { paint_index: 607 },
  "Glock-18 | Winterized": { paint_index: 1158 },
  "Glock-18 | Wraiths": { paint_index: 495 },
  "M249 | Aztec": { paint_index: 902 },
  "M249 | Blizzard Marbleized": { paint_index: 75 },
  "M249 | Bock Blocks": { paint_index: 1435 },
  "M249 | Contrast Spray": { paint_index: 22 },
  "M249 | Deep Relief": { paint_index: 983 },
  "M249 | Downtown": { paint_index: 1148 },
  "M249 | Emerald Poison Dart": { paint_index: 648 },
  "M249 | Gator Mesh": { paint_index: 243 },
  "M249 | Humidor": { paint_index: 827 },
  "M249 | Hypnosis": { paint_index: 120 },
  "M249 | Impact Drill": { paint_index: 472 },
  "M249 | Jungle": { paint_index: 151 },
  "M249 | Jungle DDPAT": { paint_index: 202 },
  "M249 | Magma": { paint_index: 266 },
  "M249 | Midnight Palm": { paint_index: 933 },
  "M249 | Nebula Crusader": { paint_index: 496 },
  "M249 | O.S.I.P.R.": { paint_index: 1042 },
  "M249 | Predator": { paint_index: 170 },
  "M249 | Sage Camo": { paint_index: 1298 },
  "M249 | Shipping Forecast": { paint_index: 452 },
  "M249 | Sleet": { paint_index: 1370 },
  "M249 | Spectre": { paint_index: 547 },
  "M249 | Spectrogram": { paint_index: 875 },
  "M249 | Submerged": { paint_index: 1242 },
  "M249 | System Lock": { paint_index: 401 },
  "M249 | Warbird": { paint_index: 900 },
  "M4A1-S | Atomic Alloy": { paint_index: 301 },
  "M4A1-S | Basilisk": { paint_index: 383 },
  "M4A1-S | Black Lotus": { paint_index: 1166 },
  "M4A1-S | Blood Tiger": { paint_index: 217 },
  "M4A1-S | Blue Phosphor": { paint_index: 1017 },
  "M4A1-S | Boreal Forest": { paint_index: 77 },
  "M4A1-S | Briefing": { paint_index: 663 },
  "M4A1-S | Bright Water": { paint_index: 189 },
  "M4A1-S | Chantico's Fire": { paint_index: 548 },
  "M4A1-S | Control Panel": { paint_index: 792 },
  "M4A1-S | Cyrex": { paint_index: 360 },
  "M4A1-S | Dark Water": { paint_index: 60 },
  "M4A1-S | Decimator": { paint_index: 644 },
  "M4A1-S | Electrum": { paint_index: 1433 },
  "M4A1-S | Emphorosaur-S": { paint_index: 1223 },
  "M4A1-S | Fade": { paint_index: 1177 },
  "M4A1-S | Fizzy POP": { paint_index: 1059 },
  "M4A1-S | Flashback": { paint_index: 631 },
  "M4A1-S | Glitched Paint": { paint_index: 1311 },
  "M4A1-S | Golden Coil": { paint_index: 497 },
  "M4A1-S | Guardian": { paint_index: 257 },
  "M4A1-S | Hot Rod": { paint_index: 445 },
  "M4A1-S | Hyper Beast": { paint_index: 430 },
  "M4A1-S | Icarus Fell": { paint_index: 440 },
  "M4A1-S | Imminent Danger": { paint_index: 1073 },
  "M4A1-S | Knight": { paint_index: 326 },
  "M4A1-S | Leaded Glass": { paint_index: 681 },
  "M4A1-S | Liquidation": { paint_index: 1340 },
  "M4A1-S | Master Piece": { paint_index: 321 },
  "M4A1-S | Mecha Industries": { paint_index: 587 },
  "M4A1-S | Moss Quartz": { paint_index: 862 },
  "M4A1-S | Mud-Spec": { paint_index: 1243 },
  "M4A1-S | Night Terror": { paint_index: 1130 },
  "M4A1-S | Nightmare": { paint_index: 714 },
  "M4A1-S | Nitro": { paint_index: 254 },
  "M4A1-S | Party Animal": { paint_index: 1376 },
  "M4A1-S | Player Two": { paint_index: 946 },
  "M4A1-S | Printstream": { paint_index: 984 },
  "M4A1-S | Rose Hex": { paint_index: 1319 },
  "M4A1-S | Solitude": { paint_index: 1338 },
  "M4A1-S | Stratosphere": { paint_index: 1216 },
  "M4A1-S | Vaporwave": { paint_index: 106 },
  "M4A1-S | VariCamo": { paint_index: 235 },
  "M4A1-S | Wash me plz": { paint_index: 160 },
  "M4A1-S | Welcome to the Jungle": { paint_index: 1001 },
  "M4A4 | Aeolian Dark": { paint_index: 1364 },
  "M4A4 | Asiimov": { paint_index: 255 },
  "M4A4 | Bullet Rain": { paint_index: 155 },
  "M4A4 | Buzz Kill": { paint_index: 632 },
  "M4A4 | Choppa": { paint_index: 1210 },
  "M4A4 | Converter": { paint_index: 793 },
  "M4A4 | Cyber Security": { paint_index: 985 },
  "M4A4 | Dark Blossom": { paint_index: 730 },
  "M4A4 | Daybreak": { paint_index: 471 },
  "M4A4 | Desert Storm": { paint_index: 8 },
  "M4A4 | Desert-Strike": { paint_index: 336 },
  "M4A4 | Desolate Space": { paint_index: 588 },
  "M4A4 | Etch Lord": { paint_index: 1165 },
  "M4A4 | Evil Daimyo": { paint_index: 480 },
  "M4A4 | Eye of Horus": { paint_index: 1255 },
  "M4A4 | Faded Zebra": { paint_index: 176 },
  "M4A4 | Full Throttle": { paint_index: 1353 },
  "M4A4 | Global Offensive": { paint_index: 993 },
  "M4A4 | Griffin": { paint_index: 384 },
  "M4A4 | Hellfire": { paint_index: 664 },
  "M4A4 | Hellish": { paint_index: 1209 },
  "M4A4 | Howl": { paint_index: 309 },
  "M4A4 | In Living Color": { paint_index: 1041 },
  "M4A4 | Jungle Tiger": { paint_index: 16 },
  "M4A4 | Magnesium": { paint_index: 811 },
  "M4A4 | Mainframe": { paint_index: 780 },
  "M4A4 | Modern Hunter": { paint_index: 164 },
  "M4A4 | Naval Shred Camo": { paint_index: 1266 },
  "M4A4 | Neo-Noir": { paint_index: 695 },
  "M4A4 | Poly Mag": { paint_index: 1149 },
  "M4A4 | Polysoup": { paint_index: 874 },
  "M4A4 | Poseidon": { paint_index: 449 },
  "M4A4 | Radiation Hazard": { paint_index: 167 },
  "M4A4 | Red DDPAT": { paint_index: 926 },
  "M4A4 | Royal Paladin": { paint_index: 512 },
  "M4A4 | Sheet Lightning": { paint_index: 1281 },
  "M4A4 | Spider Lily": { paint_index: 1097 },
  "M4A4 | Steel Work": { paint_index: 1313 },
  "M4A4 | Temukau": { paint_index: 1228 },
  "M4A4 | The Battlestar": { paint_index: 533 },
  "M4A4 | The Coalition": { paint_index: 1063 },
  "M4A4 | The Emperor": { paint_index: 844 },
  "M4A4 | Tooth Fairy": { paint_index: 971 },
  "M4A4 | Tornado": { paint_index: 101 },
  "M4A4 | Turbine": { paint_index: 118 },
  "M4A4 | Urban DDPAT": { paint_index: 17 },
  "M4A4 | X-Ray": { paint_index: 215 },
  "M4A4 | Zirka": { paint_index: 187 },
  "M4A4 | Zubastick": { paint_index: 1432 },
  "M4A4 | 龍王": { paint_index: 400 },
  "MAC-10 | Acid Hex": { paint_index: 1295 },
  "MAC-10 | Allure": { paint_index: 965 },
  "MAC-10 | Aloha": { paint_index: 665 },
  "MAC-10 | Amber Fade": { paint_index: 246 },
  "MAC-10 | Bronzer": { paint_index: 1334 },
  "MAC-10 | Button Masher": { paint_index: 1045 },
  "MAC-10 | Calf Skin": { paint_index: 748 },
  "MAC-10 | Candy Apple": { paint_index: 3 },
  "MAC-10 | Carnivore": { paint_index: 589 },
  "MAC-10 | Case Hardened": { paint_index: 44 },
  "MAC-10 | Cat Fight": { paint_index: 1349 },
  "MAC-10 | Classic Crate": { paint_index: 908 },
  "MAC-10 | Commuter": { paint_index: 343 },
  "MAC-10 | Copper Borre": { paint_index: 761 },
  "MAC-10 | Curse": { paint_index: 310 },
  "MAC-10 | Derailment": { paint_index: 1204 },
  "MAC-10 | Disco Tech": { paint_index: 947 },
  "MAC-10 | Echoing Sands": { paint_index: 1244 },
  "MAC-10 | Ensnared": { paint_index: 1131 },
  "MAC-10 | Fade": { paint_index: 38 },
  "MAC-10 | Gold Brick": { paint_index: 1025 },
  "MAC-10 | Graven": { paint_index: 188 },
  "MAC-10 | Heat": { paint_index: 284 },
  "MAC-10 | Hot Snakes": { paint_index: 1009 },
  "MAC-10 | Indigo": { paint_index: 333 },
  "MAC-10 | Lapis Gator": { paint_index: 534 },
  "MAC-10 | Last Dive": { paint_index: 651 },
  "MAC-10 | Light Box": { paint_index: 1164 },
  "MAC-10 | Malachite": { paint_index: 402 },
  "MAC-10 | Monkeyflage": { paint_index: 1150 },
  "MAC-10 | Neon Rider": { paint_index: 433 },
  "MAC-10 | Nuclear Garden": { paint_index: 372 },
  "MAC-10 | Oceanic": { paint_index: 682 },
  "MAC-10 | Palm": { paint_index: 157 },
  "MAC-10 | Pipe Down": { paint_index: 812 },
  "MAC-10 | Pipsqueak": { paint_index: 140 },
  "MAC-10 | Poplar Thicket": { paint_index: 1285 },
  "MAC-10 | Propaganda": { paint_index: 1067 },
  "MAC-10 | Rangeen": { paint_index: 498 },
  "MAC-10 | Red Filigree": { paint_index: 742 },
  "MAC-10 | Saibā Oni": { paint_index: 126 },
  "MAC-10 | Sakkaku": { paint_index: 1229 },
  "MAC-10 | Sienna Damask": { paint_index: 826 },
  "MAC-10 | Silver": { paint_index: 32 },
  "MAC-10 | Snow Splash": { paint_index: 1367 },
  "MAC-10 | Stalker": { paint_index: 898 },
  "MAC-10 | Storm Camo": { paint_index: 1269 },
  "MAC-10 | Strats": { paint_index: 1075 },
  "MAC-10 | Surfwood": { paint_index: 871 },
  "MAC-10 | Tatter": { paint_index: 337 },
  "MAC-10 | Tornado": { paint_index: 101 },
  "MAC-10 | Toybox": { paint_index: 1098 },
  "MAC-10 | Ultraviolet": { paint_index: 98 },
  "MAC-10 | Urban DDPAT": { paint_index: 17 },
  "MAC-10 | Whitefish": { paint_index: 840 },
  "MAG-7 | BI83 Spectrum": { paint_index: 1089 },
  "MAG-7 | Bulldozer": { paint_index: 39 },
  "MAG-7 | Carbon Fiber": { paint_index: 70 },
  "MAG-7 | Chainmail": { paint_index: 327 },
  "MAG-7 | Cinquedea": { paint_index: 737 },
  "MAG-7 | Cobalt Core": { paint_index: 499 },
  "MAG-7 | Copper Coated": { paint_index: 1245 },
  "MAG-7 | Copper Oxide": { paint_index: 1306 },
  "MAG-7 | Core Breach": { paint_index: 787 },
  "MAG-7 | Counter Terrace": { paint_index: 462 },
  "MAG-7 | Firestarter": { paint_index: 385 },
  "MAG-7 | Foresight": { paint_index: 1132 },
  "MAG-7 | Hard Water": { paint_index: 666 },
  "MAG-7 | Hazard": { paint_index: 198 },
  "MAG-7 | Heat": { paint_index: 431 },
  "MAG-7 | Heaven Guard": { paint_index: 291 },
  "MAG-7 | Insomnia": { paint_index: 1220 },
  "MAG-7 | Irradiated Alert": { paint_index: 171 },
  "MAG-7 | Justice": { paint_index: 948 },
  "MAG-7 | MAGnitude": { paint_index: 1355 },
  "MAG-7 | Memento": { paint_index: 177 },
  "MAG-7 | Metallic DDPAT": { paint_index: 34 },
  "MAG-7 | Monster Call": { paint_index: 961 },
  "MAG-7 | Navy Sheen": { paint_index: 822 },
  "MAG-7 | Petroglyph": { paint_index: 608 },
  "MAG-7 | Popdog": { paint_index: 909 },
  "MAG-7 | Praetorian": { paint_index: 535 },
  "MAG-7 | Prism Terrace": { paint_index: 1072 },
  "MAG-7 | Resupply": { paint_index: 1188 },
  "MAG-7 | Rust Coat": { paint_index: 754 },
  "MAG-7 | SWAG-7": { paint_index: 703 },
  "MAG-7 | Sand Dune": { paint_index: 99 },
  "MAG-7 | Seabird": { paint_index: 473 },
  "MAG-7 | Silver": { paint_index: 32 },
  "MAG-7 | Sonar": { paint_index: 633 },
  "MAG-7 | Storm": { paint_index: 100 },
  "MAG-7 | Wildwood": { paint_index: 773 },
  "MP5-SD | Acid Wash": { paint_index: 888 },
  "MP5-SD | Agent": { paint_index: 915 },
  "MP5-SD | Autumn Twilly": { paint_index: 1061 },
  "MP5-SD | Bamboo Garden": { paint_index: 872 },
  "MP5-SD | Co-Processor": { paint_index: 781 },
  "MP5-SD | Condition Zero": { paint_index: 986 },
  "MP5-SD | Desert Strike": { paint_index: 949 },
  "MP5-SD | Dirt Drop": { paint_index: 753 },
  "MP5-SD | Focus": { paint_index: 1344 },
  "MP5-SD | Gauss": { paint_index: 846 },
  "MP5-SD | Gold Leaf": { paint_index: 1294 },
  "MP5-SD | Kitbash": { paint_index: 974 },
  "MP5-SD | Lab Rats": { paint_index: 800 },
  "MP5-SD | Lime Hex": { paint_index: 1274 },
  "MP5-SD | Liquidation": { paint_index: 1231 },
  "MP5-SD | Necro Jr.": { paint_index: 1137 },
  "MP5-SD | Neon Squeezer": { paint_index: 161 },
  "MP5-SD | Nitro": { paint_index: 798 },
  "MP5-SD | Oxide Oasis": { paint_index: 923 },
  "MP5-SD | Phosphor": { paint_index: 810 },
  "MP5-SD | Picnic": { paint_index: 1385 },
  "MP5-SD | Savannah Halftone": { paint_index: 768 },
  "MP5-SD | Snow Splash": { paint_index: 1366 },
  "MP5-SD | Statics": { paint_index: 1180 },
  "MP7 | Abyssal Apparition": { paint_index: 1133 },
  "MP7 | Akoben": { paint_index: 649 },
  "MP7 | Amberline": { paint_index: 1436 },
  "MP7 | Anodized Navy": { paint_index: 28 },
  "MP7 | Armor Core": { paint_index: 423 },
  "MP7 | Army Recon": { paint_index: 245 },
  "MP7 | Asterion": { paint_index: 442 },
  "MP7 | Astrolabe": { paint_index: 940 },
  "MP7 | Bloodsport": { paint_index: 696 },
  "MP7 | Cirrus": { paint_index: 627 },
  "MP7 | Coral Paisley": { paint_index: 1386 },
  "MP7 | Fade": { paint_index: 752 },
  "MP7 | Forest DDPAT": { paint_index: 5 },
  "MP7 | Full Stop": { paint_index: 250 },
  "MP7 | Groundwater": { paint_index: 209 },
  "MP7 | Guerrilla": { paint_index: 1096 },
  "MP7 | Gunsmoke": { paint_index: 15 },
  "MP7 | Impire": { paint_index: 536 },
  "MP7 | Just Smile": { paint_index: 1163 },
  "MP7 | Mischief": { paint_index: 847 },
  "MP7 | Motherboard": { paint_index: 782 },
  "MP7 | Nemesis": { paint_index: 481 },
  "MP7 | Neon Ply": { paint_index: 893 },
  "MP7 | Ocean Foam": { paint_index: 213 },
  "MP7 | Olive Plaid": { paint_index: 365 },
  "MP7 | Orange Peel": { paint_index: 141 },
  "MP7 | Powercore": { paint_index: 719 },
  "MP7 | Prey": { paint_index: 935 },
  "MP7 | Scorched": { paint_index: 175 },
  "MP7 | Short Ochre": { paint_index: 1326 },
  "MP7 | Skulls": { paint_index: 11 },
  "MP7 | Smoking Kills": { paint_index: 1354 },
  "MP7 | Special Delivery": { paint_index: 500 },
  "MP7 | Sunbaked": { paint_index: 1246 },
  "MP7 | Tall Grass": { paint_index: 1023 },
  "MP7 | Teal Blossom": { paint_index: 728 },
  "MP7 | Urban Hazard": { paint_index: 354 },
  "MP7 | Vault Heist": { paint_index: 1007 },
  "MP7 | Whiteout": { paint_index: 102 },
  "MP9 | Airlock": { paint_index: 609 },
  "MP9 | Arctic Tri-Tone": { paint_index: 331 },
  "MP9 | Army Sheen": { paint_index: 298 },
  "MP9 | Bee-Tron": { paint_index: 1388 },
  "MP9 | Bioleak": { paint_index: 549 },
  "MP9 | Black Sand": { paint_index: 697 },
  "MP9 | Broken Record": { paint_index: 1341 },
  "MP9 | Buff Blue": { paint_index: 1278 },
  "MP9 | Bulldozer": { paint_index: 39 },
  "MP9 | Capillary": { paint_index: 715 },
  "MP9 | Cobalt Paisley": { paint_index: 1258 },
  "MP9 | Dark Age": { paint_index: 329 },
  "MP9 | Dart": { paint_index: 386 },
  "MP9 | Deadly Poison": { paint_index: 403 },
  "MP9 | Dizzy": { paint_index: 1375 },
  "MP9 | Dry Season": { paint_index: 199 },
  "MP9 | Featherweight": { paint_index: 1225 },
  "MP9 | Food Chain": { paint_index: 1037 },
  "MP9 | Goo": { paint_index: 679 },
  "MP9 | Green Plaid": { paint_index: 366 },
  "MP9 | Hot Rod": { paint_index: 33 },
  "MP9 | Hydra": { paint_index: 910 },
  "MP9 | Hypnotic": { paint_index: 61 },
  "MP9 | Latte Rush": { paint_index: 1211 },
  "MP9 | Modest Threat": { paint_index: 804 },
  "MP9 | Mount Fuji": { paint_index: 1094 },
  "MP9 | Multi-Terrain": { paint_index: 1330 },
  "MP9 | Music Box": { paint_index: 820 },
  "MP9 | Nexus": { paint_index: 1193 },
  "MP9 | Old Roots": { paint_index: 931 },
  "MP9 | Orange Peel": { paint_index: 141 },
  "MP9 | Pandora's Box": { paint_index: 448 },
  "MP9 | Pine": { paint_index: 1301 },
  "MP9 | Rose Iron": { paint_index: 262 },
  "MP9 | Ruby Poison Dart": { paint_index: 482 },
  "MP9 | Sand Dashed": { paint_index: 148 },
  "MP9 | Sand Scale": { paint_index: 630 },
  "MP9 | Setting Sun": { paint_index: 368 },
  "MP9 | Shredded": { paint_index: 1310 },
  "MP9 | Slide": { paint_index: 755 },
  "MP9 | Stained Glass": { paint_index: 867 },
  "MP9 | Starlight Protector": { paint_index: 1134 },
  "MP9 | Storm": { paint_index: 100 },
  "MP9 | Urban Sovereign": { paint_index: 1423 },
  "MP9 | Wild Lily": { paint_index: 734 },
  "Negev | Anodized Navy": { paint_index: 28 },
  "Negev | Army Sheen": { paint_index: 298 },
  "Negev | Boroque Sand": { paint_index: 920 },
  "Negev | Bratatat": { paint_index: 317 },
  "Negev | Bulkhead": { paint_index: 783 },
  "Negev | CaliCamo": { paint_index: 240 },
  "Negev | Dazzle": { paint_index: 610 },
  "Negev | Desert-Strike": { paint_index: 355 },
  "Negev | Drop Me": { paint_index: 1152 },
  "Negev | Infrastructure": { paint_index: 1080 },
  "Negev | Lionfish": { paint_index: 698 },
  "Negev | Loudmouth": { paint_index: 483 },
  "Negev | Man-o'-war": { paint_index: 432 },
  "Negev | Mjölnir": { paint_index: 763 },
  "Negev | Nuclear Waste": { paint_index: 369 },
  "Negev | Palm": { paint_index: 201 },
  "Negev | Phoenix Stencil": { paint_index: 1012 },
  "Negev | Power Loader": { paint_index: 514 },
  "Negev | Prototype": { paint_index: 950 },
  "Negev | Raw Ceramic": { paint_index: 1300 },
  "Negev | Sour Grapes": { paint_index: 1260 },
  "Negev | Terrain": { paint_index: 285 },
  "Negev | Ultralight": { paint_index: 958 },
  "Negev | Wall Bang": { paint_index: 144 },
  "Negev | dev_texture": { paint_index: 1043 },
  "Nova | Antique": { paint_index: 286 },
  "Nova | Army Sheen": { paint_index: 298 },
  "Nova | Baroque Orange": { paint_index: 746 },
  "Nova | Blaze Orange": { paint_index: 166 },
  "Nova | Bloomstick": { paint_index: 62 },
  "Nova | Caged Steel": { paint_index: 299 },
  "Nova | Candy Apple": { paint_index: 3 },
  "Nova | Clear Polymer": { paint_index: 987 },
  "Nova | Currents": { paint_index: 1368 },
  "Nova | Dark Sigil": { paint_index: 1162 },
  "Nova | Exo": { paint_index: 590 },
  "Nova | Forest Leaves": { paint_index: 25 },
  "Nova | Ghost Camo": { paint_index: 225 },
  "Nova | Gila": { paint_index: 634 },
  "Nova | Graphite": { paint_index: 214 },
  "Nova | Green Apple": { paint_index: 294 },
  "Nova | Hyper Beast": { paint_index: 537 },
  "Nova | Interlock": { paint_index: 1077 },
  "Nova | Koi": { paint_index: 356 },
  "Nova | Mandrel": { paint_index: 785 },
  "Nova | Marsh Grass": { paint_index: 1331 },
  "Nova | Modern Hunter": { paint_index: 164 },
  "Nova | Moon in Libra": { paint_index: 450 },
  "Nova | Ocular": { paint_index: 1350 },
  "Nova | Plume": { paint_index: 890 },
  "Nova | Polar Mesh": { paint_index: 107 },
  "Nova | Predator": { paint_index: 170 },
  "Nova | Quick Sand": { paint_index: 929 },
  "Nova | Rain Station": { paint_index: 1337 },
  "Nova | Ranger": { paint_index: 484 },
  "Nova | Red Quartz": { paint_index: 248 },
  "Nova | Rising Skull": { paint_index: 263 },
  "Nova | Rising Sun": { paint_index: 1192 },
  "Nova | Rust Coat": { paint_index: 323 },
  "Nova | Sand Dune": { paint_index: 99 },
  "Nova | Sobek's Bite": { paint_index: 1247 },
  "Nova | Tempest": { paint_index: 191 },
  "Nova | Toy Soldier": { paint_index: 716 },
  "Nova | Turquoise Pour": { paint_index: 1261 },
  "Nova | Walnut": { paint_index: 158 },
  "Nova | Wild Six": { paint_index: 699 },
  "Nova | Windblown": { paint_index: 1051 },
  "Nova | Wood Fired": { paint_index: 809 },
  "Nova | Wurst Hölle": { paint_index: 145 },
  "Nova | Yorkshire": { paint_index: 324 },
  "P2000 | Acid Etched": { paint_index: 951 },
  "P2000 | Amber Fade": { paint_index: 246 },
  "P2000 | Chainmail": { paint_index: 327 },
  "P2000 | Coach Class": { paint_index: 346 },
  "P2000 | Coral Halftone": { paint_index: 878 },
  "P2000 | Corticera": { paint_index: 184 },
  "P2000 | Dispatch": { paint_index: 997 },
  "P2000 | Fire Elemental": { paint_index: 389 },
  "P2000 | Gnarled": { paint_index: 960 },
  "P2000 | Granite Marbleized": { paint_index: 21 },
  "P2000 | Grassland": { paint_index: 95 },
  "P2000 | Grassland Leaves": { paint_index: 104 },
  "P2000 | Grip Tape": { paint_index: 1359 },
  "P2000 | Handgun": { paint_index: 485 },
  "P2000 | Imperial": { paint_index: 515 },
  "P2000 | Imperial Dragon": { paint_index: 591 },
  "P2000 | Ivory": { paint_index: 357 },
  "P2000 | Lifted Spirits": { paint_index: 1138 },
  "P2000 | Marsh": { paint_index: 1292 },
  "P2000 | Obsidian": { paint_index: 894 },
  "P2000 | Ocean Foam": { paint_index: 211 },
  "P2000 | Oceanic": { paint_index: 550 },
  "P2000 | Panther Camo": { paint_index: 1019 },
  "P2000 | Pathfinder": { paint_index: 443 },
  "P2000 | Pulse": { paint_index: 338 },
  "P2000 | Red FragCam": { paint_index: 275 },
  "P2000 | Red Wing": { paint_index: 1342 },
  "P2000 | Royal Baroque": { paint_index: 1259 },
  "P2000 | Scorpion": { paint_index: 71 },
  "P2000 | Silver": { paint_index: 32 },
  "P2000 | Space Race": { paint_index: 1055 },
  "P2000 | Sure Grip": { paint_index: 1181 },
  "P2000 | Turf": { paint_index: 635 },
  "P2000 | Urban Hazard": { paint_index: 700 },
  "P2000 | Wicked Sick": { paint_index: 1224 },
  "P2000 | Woodsman": { paint_index: 667 },
  "P250 | Apep's Curse": { paint_index: 1248 },
  "P250 | Asiimov": { paint_index: 551 },
  "P250 | Bengal Tiger": { paint_index: 1030 },
  "P250 | Black & Tan": { paint_index: 928 },
  "P250 | Bone Mask": { paint_index: 27 },
  "P250 | Boreal Forest": { paint_index: 77 },
  "P250 | Bullfrog": { paint_index: 1345 },
  "P250 | Cartel": { paint_index: 388 },
  "P250 | Cassette": { paint_index: 968 },
  "P250 | Constructivist": { paint_index: 1212 },
  "P250 | Contaminant": { paint_index: 982 },
  "P250 | Contamination": { paint_index: 373 },
  "P250 | Copper Oxide": { paint_index: 1307 },
  "P250 | Crimson Kimono": { paint_index: 466 },
  "P250 | Cyber Shell": { paint_index: 1044 },
  "P250 | Dark Filigree": { paint_index: 741 },
  "P250 | Digital Architect": { paint_index: 1081 },
  "P250 | Drought": { paint_index: 825 },
  "P250 | Epicenter": { paint_index: 130 },
  "P250 | Exchanger": { paint_index: 786 },
  "P250 | Facets": { paint_index: 207 },
  "P250 | Facility Draft": { paint_index: 777 },
  "P250 | Forest Night": { paint_index: 78 },
  "P250 | Franklin": { paint_index: 295 },
  "P250 | Gunsmoke": { paint_index: 15 },
  "P250 | Hive": { paint_index: 219 },
  "P250 | Inferno": { paint_index: 907 },
  "P250 | Iron Clad": { paint_index: 592 },
  "P250 | Kintsugi": { paint_index: 1420 },
  "P250 | Mehndi": { paint_index: 258 },
  "P250 | Metallic DDPAT": { paint_index: 34 },
  "P250 | Mint Kimono": { paint_index: 467 },
  "P250 | Modern Hunter": { paint_index: 164 },
  "P250 | Muertos": { paint_index: 404 },
  "P250 | Nevermore": { paint_index: 813 },
  "P250 | Nuclear Threat": { paint_index: 168 },
  "P250 | Plum Netting": { paint_index: 1273 },
  "P250 | Re.built": { paint_index: 1230 },
  "P250 | Red Rock": { paint_index: 668 },
  "P250 | Red Tide": { paint_index: 1315 },
  "P250 | Ripple": { paint_index: 650 },
  "P250 | Sand Dune": { paint_index: 99 },
  "P250 | Sedimentary": { paint_index: 1317 },
  "P250 | See Ya Later": { paint_index: 678 },
  "P250 | Sleet": { paint_index: 1369 },
  "P250 | Small Game": { paint_index: 774 },
  "P250 | Splash": { paint_index: 162 },
  "P250 | Steel Disruption": { paint_index: 230 },
  "P250 | Supernova": { paint_index: 358 },
  "P250 | Undertow": { paint_index: 271 },
  "P250 | Valence": { paint_index: 426 },
  "P250 | Verdigris": { paint_index: 848 },
  "P250 | Vino Primo": { paint_index: 749 },
  "P250 | Visions": { paint_index: 1153 },
  "P250 | Whiteout": { paint_index: 102 },
  "P250 | Wingshot": { paint_index: 501 },
  "P250 | X-Ray": { paint_index: 125 },
  "P90 | Aeolian Light": { paint_index: 1361 },
  "P90 | Ancient Earth": { paint_index: 1020 },
  "P90 | Ash Wood": { paint_index: 234 },
  "P90 | Asiimov": { paint_index: 359 },
  "P90 | Astral Jörmungandr": { paint_index: 759 },
  "P90 | Attack Vector": { paint_index: 936 },
  "P90 | Baroque Red": { paint_index: 744 },
  "P90 | Blind Spot": { paint_index: 228 },
  "P90 | Blue Tac": { paint_index: 1277 },
  "P90 | Chopper": { paint_index: 593 },
  "P90 | Cocoa Rampage": { paint_index: 977 },
  "P90 | Cold Blooded": { paint_index: 67 },
  "P90 | Death Grip": { paint_index: 669 },
  "P90 | Death by Kitty": { paint_index: 156 },
  "P90 | Deathgaze": { paint_index: 1419 },
  "P90 | Desert DDPAT": { paint_index: 925 },
  "P90 | Desert Halftone": { paint_index: 1332 },
  "P90 | Desert Warfare": { paint_index: 311 },
  "P90 | Elite Build": { paint_index: 486 },
  "P90 | Emerald Dragon": { paint_index: 182 },
  "P90 | Facility Negative": { paint_index: 776 },
  "P90 | Fallout Warning": { paint_index: 169 },
  "P90 | Freight": { paint_index: 969 },
  "P90 | Glacier Mesh": { paint_index: 111 },
  "P90 | Grim": { paint_index: 611 },
  "P90 | Leather": { paint_index: 342 },
  "P90 | Module": { paint_index: 335 },
  "P90 | Mustard Gas": { paint_index: 1291 },
  "P90 | Neoqueen": { paint_index: 1233 },
  "P90 | Nostalgia": { paint_index: 911 },
  "P90 | Off World": { paint_index: 849 },
  "P90 | Randy Rush": { paint_index: 127 },
  "P90 | Reef Grief": { paint_index: 1256 },
  "P90 | Run and Hide": { paint_index: 1000 },
  "P90 | Sand Spray": { paint_index: 124 },
  "P90 | ScaraB Rush": { paint_index: 1250 },
  "P90 | Schematic": { paint_index: 1074 },
  "P90 | Scorched": { paint_index: 175 },
  "P90 | Shallow Grave": { paint_index: 636 },
  "P90 | Shapewood": { paint_index: 516 },
  "P90 | Storm": { paint_index: 100 },
  "P90 | Straight Dimes": { paint_index: 1199 },
  "P90 | Sunset Lily": { paint_index: 726 },
  "P90 | Teardown": { paint_index: 244 },
  "P90 | Tiger Pit": { paint_index: 1015 },
  "P90 | Traction": { paint_index: 717 },
  "P90 | Trigon": { paint_index: 283 },
  "P90 | Vent Rush": { paint_index: 1154 },
  "P90 | Verdant Growth": { paint_index: 828 },
  "P90 | Virus": { paint_index: 20 },
  "P90 | Wash me": { paint_index: 133 },
  "P90 | Wave Breaker": { paint_index: 1190 },
  "PP-Bizon | Anolis": { paint_index: 829 },
  "PP-Bizon | Antique": { paint_index: 306 },
  "PP-Bizon | Bamboo Print": { paint_index: 457 },
  "PP-Bizon | Bizoom": { paint_index: 1374 },
  "PP-Bizon | Blue Streak": { paint_index: 13 },
  "PP-Bizon | Brass": { paint_index: 159 },
  "PP-Bizon | Breaker Box": { paint_index: 1083 },
  "PP-Bizon | Candy Apple": { paint_index: 3 },
  "PP-Bizon | Carbon Fiber": { paint_index: 70 },
  "PP-Bizon | Chemical Green": { paint_index: 376 },
  "PP-Bizon | Cobalt Halftone": { paint_index: 267 },
  "PP-Bizon | Cold Cell": { paint_index: 770 },
  "PP-Bizon | Death Rattle": { paint_index: 293 },
  "PP-Bizon | Embargo": { paint_index: 884 },
  "PP-Bizon | Facility Sketch": { paint_index: 775 },
  "PP-Bizon | Forest Leaves": { paint_index: 25 },
  "PP-Bizon | Fuel Rod": { paint_index: 508 },
  "PP-Bizon | Harvester": { paint_index: 594 },
  "PP-Bizon | High Roller": { paint_index: 676 },
  "PP-Bizon | Irradiated Alert": { paint_index: 171 },
  "PP-Bizon | Judgement of Anubis": { paint_index: 542 },
  "PP-Bizon | Jungle Slipstream": { paint_index: 641 },
  "PP-Bizon | Lumen": { paint_index: 1099 },
  "PP-Bizon | Modern Hunter": { paint_index: 164 },
  "PP-Bizon | Night Ops": { paint_index: 236 },
  "PP-Bizon | Night Riot": { paint_index: 692 },
  "PP-Bizon | Osiris": { paint_index: 349 },
  "PP-Bizon | Photic Zone": { paint_index: 526 },
  "PP-Bizon | RMX": { paint_index: 1418 },
  "PP-Bizon | Runic": { paint_index: 973 },
  "PP-Bizon | Rust Coat": { paint_index: 203 },
  "PP-Bizon | Sand Dashed": { paint_index: 148 },
  "PP-Bizon | Seabird": { paint_index: 873 },
  "PP-Bizon | Space Cat": { paint_index: 1125 },
  "PP-Bizon | Thermal Currents": { paint_index: 1392 },
  "PP-Bizon | Urban Dashed": { paint_index: 149 },
  "PP-Bizon | Water Sigil": { paint_index: 224 },
  "PP-Bizon | Wood Block Camo": { paint_index: 1325 },
  "R8 Revolver | Amber Fade": { paint_index: 523 },
  "R8 Revolver | Banana Cannon": { paint_index: 1232 },
  "R8 Revolver | Blaze": { paint_index: 37 },
  "R8 Revolver | Bone Forged": { paint_index: 952 },
  "R8 Revolver | Bone Mask": { paint_index: 27 },
  "R8 Revolver | Canal Spray": { paint_index: 866 },
  "R8 Revolver | Cobalt Grip": { paint_index: 1276 },
  "R8 Revolver | Crazy 8": { paint_index: 1145 },
  "R8 Revolver | Crimson Web": { paint_index: 12 },
  "R8 Revolver | Dark Chamber": { paint_index: 1363 },
  "R8 Revolver | Desert Brush": { paint_index: 924 },
  "R8 Revolver | Fade": { paint_index: 522 },
  "R8 Revolver | Grip": { paint_index: 701 },
  "R8 Revolver | Inlay": { paint_index: 1237 },
  "R8 Revolver | Junk Yard": { paint_index: 1047 },
  "R8 Revolver | Leafhopper": { paint_index: 1293 },
  "R8 Revolver | Llama Cannon": { paint_index: 683 },
  "R8 Revolver | Mauve Aside": { paint_index: 1389 },
  "R8 Revolver | Memento": { paint_index: 892 },
  "R8 Revolver | Night": { paint_index: 40 },
  "R8 Revolver | Nitro": { paint_index: 798 },
  "R8 Revolver | Phoenix Marker": { paint_index: 1011 },
  "R8 Revolver | Reboot": { paint_index: 595 },
  "R8 Revolver | Skull Crusher": { paint_index: 843 },
  "R8 Revolver | Survivalist": { paint_index: 721 },
  "R8 Revolver | Tango": { paint_index: 123 },
  "SCAR-20 | Army Sheen": { paint_index: 298 },
  "SCAR-20 | Assault": { paint_index: 914 },
  "SCAR-20 | Bloodsport": { paint_index: 597 },
  "SCAR-20 | Blueprint": { paint_index: 642 },
  "SCAR-20 | Brass": { paint_index: 159 },
  "SCAR-20 | Caged": { paint_index: 1343 },
  "SCAR-20 | Carbon Fiber": { paint_index: 70 },
  "SCAR-20 | Cardiac": { paint_index: 391 },
  "SCAR-20 | Contractor": { paint_index: 46 },
  "SCAR-20 | Crimson Web": { paint_index: 232 },
  "SCAR-20 | Cyrex": { paint_index: 312 },
  "SCAR-20 | Emerald": { paint_index: 196 },
  "SCAR-20 | Enforcer": { paint_index: 954 },
  "SCAR-20 | Fragments": { paint_index: 1226 },
  "SCAR-20 | Green Marine": { paint_index: 502 },
  "SCAR-20 | Grotto": { paint_index: 406 },
  "SCAR-20 | Jungle Slipstream": { paint_index: 685 },
  "SCAR-20 | Magna Carta": { paint_index: 1028 },
  "SCAR-20 | Outbreak": { paint_index: 518 },
  "SCAR-20 | Palm": { paint_index: 157 },
  "SCAR-20 | Poultrygeist": { paint_index: 1139 },
  "SCAR-20 | Powercore": { paint_index: 612 },
  "SCAR-20 | Sand Mesh": { paint_index: 116 },
  "SCAR-20 | Short Ochre": { paint_index: 1327 },
  "SCAR-20 | Splash Jam": { paint_index: 165 },
  "SCAR-20 | Stone Mosaico": { paint_index: 865 },
  "SCAR-20 | Storm": { paint_index: 100 },
  "SCAR-20 | Torn": { paint_index: 896 },
  "SCAR-20 | Trail Blazer": { paint_index: 117 },
  "SCAR-20 | Wild Berry": { paint_index: 883 },
  "SCAR-20 | Zinc": { paint_index: 1371 },
  "SG 553 | Aerial": { paint_index: 598 },
  "SG 553 | Aloha": { paint_index: 702 },
  "SG 553 | Anodized Navy": { paint_index: 28 },
  "SG 553 | Army Sheen": { paint_index: 298 },
  "SG 553 | Atlas": { paint_index: 553 },
  "SG 553 | Barricade": { paint_index: 861 },
  "SG 553 | Basket Halftone": { paint_index: 1320 },
  "SG 553 | Berry Gel Coat": { paint_index: 901 },
  "SG 553 | Bleached": { paint_index: 934 },
  "SG 553 | Bulldozer": { paint_index: 39 },
  "SG 553 | Candy Apple": { paint_index: 864 },
  "SG 553 | Colony IV": { paint_index: 897 },
  "SG 553 | Cyberforce": { paint_index: 1234 },
  "SG 553 | Cyrex": { paint_index: 487 },
  "SG 553 | Damascus Steel": { paint_index: 247 },
  "SG 553 | Danger Close": { paint_index: 815 },
  "SG 553 | Darkwing": { paint_index: 955 },
  "SG 553 | Desert Blossom": { paint_index: 765 },
  "SG 553 | Dragon Tech": { paint_index: 1151 },
  "SG 553 | Fallout Warning": { paint_index: 378 },
  "SG 553 | Gator Mesh": { paint_index: 243 },
  "SG 553 | Hazard Pay": { paint_index: 1084 },
  "SG 553 | Heavy Metal": { paint_index: 1048 },
  "SG 553 | Hypnotic": { paint_index: 61 },
  "SG 553 | Integrale": { paint_index: 750 },
  "SG 553 | Lush Ruins": { paint_index: 1022 },
  "SG 553 | Night Camo": { paint_index: 1270 },
  "SG 553 | Ol' Rusty": { paint_index: 966 },
  "SG 553 | Phantom": { paint_index: 686 },
  "SG 553 | Pulse": { paint_index: 287 },
  "SG 553 | Safari Print": { paint_index: 1394 },
  "SG 553 | Tiger Moth": { paint_index: 519 },
  "SG 553 | Tornado": { paint_index: 101 },
  "SG 553 | Traveler": { paint_index: 363 },
  "SG 553 | Triarch": { paint_index: 613 },
  "SG 553 | Ultraviolet": { paint_index: 98 },
  "SG 553 | Wave Spray": { paint_index: 186 },
  "SG 553 | Waves Perforated": { paint_index: 136 },
  "SSG 08 | Abyss": { paint_index: 361 },
  "SSG 08 | Acid Fade": { paint_index: 253 },
  "SSG 08 | Azure Glyph": { paint_index: 1251 },
  "SSG 08 | Big Iron": { paint_index: 503 },
  "SSG 08 | Blood in the Water": { paint_index: 222 },
  "SSG 08 | Bloodshot": { paint_index: 899 },
  "SSG 08 | Blue Spruce": { paint_index: 96 },
  "SSG 08 | Blush Pour": { paint_index: 1316 },
  "SSG 08 | Calligrafaux": { paint_index: 1379 },
  "SSG 08 | Carbon Fiber": { paint_index: 70 },
  "SSG 08 | Dark Water": { paint_index: 60 },
  "SSG 08 | Death Strike": { paint_index: 1052 },
  "SSG 08 | Death's Head": { paint_index: 670 },
  "SSG 08 | Detour": { paint_index: 319 },
  "SSG 08 | Dezastre": { paint_index: 1161 },
  "SSG 08 | Dragonfire": { paint_index: 624 },
  "SSG 08 | Fever Dream": { paint_index: 956 },
  "SSG 08 | Ghost Crusader": { paint_index: 554 },
  "SSG 08 | Green Ceramic": { paint_index: 1304 },
  "SSG 08 | Grey Smoke": { paint_index: 1271 },
  "SSG 08 | Halftone Whorl": { paint_index: 877 },
  "SSG 08 | Hand Brake": { paint_index: 751 },
  "SSG 08 | Jungle Dashed": { paint_index: 147 },
  "SSG 08 | Lichen Dashed": { paint_index: 26 },
  "SSG 08 | Mainframe 001": { paint_index: 967 },
  "SSG 08 | Mayan Dreams": { paint_index: 200 },
  "SSG 08 | Memorial": { paint_index: 1187 },
  "SSG 08 | Necropos": { paint_index: 538 },
  "SSG 08 | Orange Filigree": { paint_index: 743 },
  "SSG 08 | Parallax": { paint_index: 989 },
  "SSG 08 | Prey": { paint_index: 935 },
  "SSG 08 | Rapid Transit": { paint_index: 128 },
  "SSG 08 | Red Stone": { paint_index: 762 },
  "SSG 08 | Sand Dune": { paint_index: 99 },
  "SSG 08 | Sans Comic": { paint_index: 1372 },
  "SSG 08 | Sea Calico": { paint_index: 868 },
  "SSG 08 | Slashed": { paint_index: 304 },
  "SSG 08 | Spring Twilly": { paint_index: 1060 },
  "SSG 08 | Threat Detected": { paint_index: 996 },
  "SSG 08 | Tiger Tear": { paint_index: 1289 },
  "SSG 08 | Tropical Storm": { paint_index: 233 },
  "SSG 08 | Turbo Peek": { paint_index: 1101 },
  "SSG 08 | Zeno": { paint_index: 513 },
  "Sawed-Off | Amber Fade": { paint_index: 246 },
  "Sawed-Off | Analog Input": { paint_index: 1160 },
  "Sawed-Off | Apocalypto": { paint_index: 953 },
  "Sawed-Off | Bamboo Shadow": { paint_index: 458 },
  "Sawed-Off | Black Sand": { paint_index: 814 },
  "Sawed-Off | Brake Light": { paint_index: 797 },
  "Sawed-Off | Clay Ambush": { paint_index: 1014 },
  "Sawed-Off | Copper": { paint_index: 41 },
  "Sawed-Off | Crimson Batik": { paint_index: 1391 },
  "Sawed-Off | Devourer": { paint_index: 720 },
  "Sawed-Off | First Class": { paint_index: 345 },
  "Sawed-Off | Forest DDPAT": { paint_index: 5 },
  "Sawed-Off | Fubar": { paint_index: 552 },
  "Sawed-Off | Full Stop": { paint_index: 250 },
  "Sawed-Off | Fusion": { paint_index: 1427 },
  "Sawed-Off | Highwayman": { paint_index: 390 },
  "Sawed-Off | Irradiated Alert": { paint_index: 171 },
  "Sawed-Off | Jungle Thicket": { paint_index: 870 },
  "Sawed-Off | Kiss♥Love": { paint_index: 1155 },
  "Sawed-Off | Limelight": { paint_index: 596 },
  "Sawed-Off | Morris": { paint_index: 673 },
  "Sawed-Off | Mosaico": { paint_index: 204 },
  "Sawed-Off | Orange DDPAT": { paint_index: 83 },
  "Sawed-Off | Origami": { paint_index: 434 },
  "Sawed-Off | Parched": { paint_index: 880 },
  "Sawed-Off | Runoff": { paint_index: 1272 },
  "Sawed-Off | Rust Coat": { paint_index: 323 },
  "Sawed-Off | Sage Spray": { paint_index: 119 },
  "Sawed-Off | Serenity": { paint_index: 405 },
  "Sawed-Off | Snake Camo": { paint_index: 30 },
  "Sawed-Off | Spirit Board": { paint_index: 1140 },
  "Sawed-Off | The Kraken": { paint_index: 256 },
  "Sawed-Off | Wasteland Princess": { paint_index: 638 },
  "Sawed-Off | Yorick": { paint_index: 517 },
  "Sawed-Off | Zander": { paint_index: 655 },
  "Tec-9 | Army Mesh": { paint_index: 242 },
  "Tec-9 | Avalanche": { paint_index: 520 },
  "Tec-9 | Bamboo Forest": { paint_index: 459 },
  "Tec-9 | Bamboozle": { paint_index: 839 },
  "Tec-9 | Banana Leaf": { paint_index: 1384 },
  "Tec-9 | Blast From the Past": { paint_index: 1024 },
  "Tec-9 | Blue Blast": { paint_index: 1279 },
  "Tec-9 | Blue Titanium": { paint_index: 216 },
  "Tec-9 | Brass": { paint_index: 159 },
  "Tec-9 | Brother": { paint_index: 964 },
  "Tec-9 | Citric Acid": { paint_index: 1322 },
  "Tec-9 | Cracked Opal": { paint_index: 684 },
  "Tec-9 | Cut Out": { paint_index: 671 },
  "Tec-9 | Decimator": { paint_index: 889 },
  "Tec-9 | Flash Out": { paint_index: 905 },
  "Tec-9 | Fubar": { paint_index: 816 },
  "Tec-9 | Fuel Injector": { paint_index: 614 },
  "Tec-9 | Garter-9": { paint_index: 1286 },
  "Tec-9 | Groundwater": { paint_index: 2 },
  "Tec-9 | Hades": { paint_index: 439 },
  "Tec-9 | Ice Cap": { paint_index: 599 },
  "Tec-9 | Isaac": { paint_index: 303 },
  "Tec-9 | Jambiya": { paint_index: 539 },
  "Tec-9 | Mummy's Rot": { paint_index: 1252 },
  "Tec-9 | Nuclear Threat": { paint_index: 179 },
  "Tec-9 | Orange Murano": { paint_index: 738 },
  "Tec-9 | Ossified": { paint_index: 36 },
  "Tec-9 | Phoenix Chalk": { paint_index: 1010 },
  "Tec-9 | Raw Ceramic": { paint_index: 1299 },
  "Tec-9 | Re-Entry": { paint_index: 555 },
  "Tec-9 | Rebel": { paint_index: 1235 },
  "Tec-9 | Red Quartz": { paint_index: 248 },
  "Tec-9 | Remote Control": { paint_index: 791 },
  "Tec-9 | Rust Leaf": { paint_index: 733 },
  "Tec-9 | Safety Net": { paint_index: 795 },
  "Tec-9 | Sandstorm": { paint_index: 289 },
  "Tec-9 | Slag": { paint_index: 1159 },
  "Tec-9 | Snek-9": { paint_index: 722 },
  "Tec-9 | Terrace": { paint_index: 463 },
  "Tec-9 | Tiger Stencil": { paint_index: 766 },
  "Tec-9 | Titanium Bit": { paint_index: 272 },
  "Tec-9 | Tornado": { paint_index: 206 },
  "Tec-9 | Toxic": { paint_index: 374 },
  "Tec-9 | Urban DDPAT": { paint_index: 17 },
  "Tec-9 | VariCamo": { paint_index: 235 },
  "Tec-9 | Whiteout": { paint_index: 1214 },
  "UMP-45 | Arctic Wolf": { paint_index: 704 },
  "UMP-45 | Blaze": { paint_index: 37 },
  "UMP-45 | Bone Pile": { paint_index: 193 },
  "UMP-45 | Briefing": { paint_index: 615 },
  "UMP-45 | Caramel": { paint_index: 93 },
  "UMP-45 | Carbon Fiber": { paint_index: 70 },
  "UMP-45 | Continuum": { paint_index: 1351 },
  "UMP-45 | Corporal": { paint_index: 281 },
  "UMP-45 | Crime Scene": { paint_index: 1003 },
  "UMP-45 | Crimson Foil": { paint_index: 412 },
  "UMP-45 | Day Lily": { paint_index: 725 },
  "UMP-45 | Delusion": { paint_index: 392 },
  "UMP-45 | Exposure": { paint_index: 688 },
  "UMP-45 | Facility Dark": { paint_index: 778 },
  "UMP-45 | Fade": { paint_index: 879 },
  "UMP-45 | Fallout Warning": { paint_index: 169 },
  "UMP-45 | Fragment": { paint_index: 1426 },
  "UMP-45 | Full Stop": { paint_index: 250 },
  "UMP-45 | Gold Bismuth": { paint_index: 990 },
  "UMP-45 | Grand Prix": { paint_index: 436 },
  "UMP-45 | Green Swirl": { paint_index: 1303 },
  "UMP-45 | Gunsmoke": { paint_index: 15 },
  "UMP-45 | Houndstooth": { paint_index: 1008 },
  "UMP-45 | Indigo": { paint_index: 333 },
  "UMP-45 | K.O. Factory": { paint_index: 1194 },
  "UMP-45 | Labyrinth": { paint_index: 362 },
  "UMP-45 | Late Night Transit": { paint_index: 1203 },
  "UMP-45 | Mechanism": { paint_index: 1085 },
  "UMP-45 | Metal Flowers": { paint_index: 672 },
  "UMP-45 | Minotaur's Labyrinth": { paint_index: 441 },
  "UMP-45 | Momentum": { paint_index: 802 },
  "UMP-45 | Moonrise": { paint_index: 851 },
  "UMP-45 | Motorized": { paint_index: 1175 },
  "UMP-45 | Mudder": { paint_index: 90 },
  "UMP-45 | Neo-Noir": { paint_index: 131 },
  "UMP-45 | Oscillator": { paint_index: 1049 },
  "UMP-45 | Plastique": { paint_index: 916 },
  "UMP-45 | Primal Saber": { paint_index: 556 },
  "UMP-45 | Riot": { paint_index: 488 },
  "UMP-45 | Roadblock": { paint_index: 1157 },
  "UMP-45 | Scaffold": { paint_index: 652 },
  "UMP-45 | Scorched": { paint_index: 175 },
  "UMP-45 | Urban DDPAT": { paint_index: 17 },
  "UMP-45 | Warm Blooded": { paint_index: 1387 },
  "UMP-45 | Wild Child": { paint_index: 1236 },
  "USP-S | 27": { paint_index: 115 },
  "USP-S | Alpine Camo": { paint_index: 830 },
  "USP-S | Ancient Visions": { paint_index: 1031 },
  "USP-S | Black Lotus": { paint_index: 1102 },
  "USP-S | Bleeding Edge": { paint_index: 1323 },
  "USP-S | Blood Tiger": { paint_index: 217 },
  "USP-S | Blueprint": { paint_index: 657 },
  "USP-S | Business Class": { paint_index: 364 },
  "USP-S | Caiman": { paint_index: 339 },
  "USP-S | Check Engine": { paint_index: 796 },
  "USP-S | Cortex": { paint_index: 705 },
  "USP-S | Cyrex": { paint_index: 637 },
  "USP-S | Dark Water": { paint_index: 60 },
  "USP-S | Desert Tactical": { paint_index: 1253 },
  "USP-S | Flashback": { paint_index: 817 },
  "USP-S | Forest Leaves": { paint_index: 25 },
  "USP-S | Guardian": { paint_index: 290 },
  "USP-S | Jawbreaker": { paint_index: 1173 },
  "USP-S | Kill Confirmed": { paint_index: 504 },
  "USP-S | Lead Conduit": { paint_index: 540 },
  "USP-S | Monster Mashup": { paint_index: 991 },
  "USP-S | Neo-Noir": { paint_index: 653 },
  "USP-S | Night Ops": { paint_index: 236 },
  "USP-S | Orange Anolis": { paint_index: 922 },
  "USP-S | Orion": { paint_index: 313 },
  "USP-S | Overgrowth": { paint_index: 183 },
  "USP-S | PC-GRN": { paint_index: 1186 },
  "USP-S | Para Green": { paint_index: 454 },
  "USP-S | Pathfinder": { paint_index: 443 },
  "USP-S | Printstream": { paint_index: 1142 },
  "USP-S | Purple DDPAT": { paint_index: 818 },
  "USP-S | Road Rash": { paint_index: 318 },
  "USP-S | Royal Blue": { paint_index: 332 },
  "USP-S | Royal Guard": { paint_index: 1217 },
  "USP-S | Serum": { paint_index: 221 },
  "USP-S | Silent Shot": { paint_index: 1431 },
  "USP-S | Sleeping Potion": { paint_index: 1377 },
  "USP-S | Stainless": { paint_index: 277 },
  "USP-S | Target Acquired": { paint_index: 1027 },
  "USP-S | The Traitor": { paint_index: 1040 },
  "USP-S | Ticket to Hell": { paint_index: 1136 },
  "USP-S | Torque": { paint_index: 489 },
  "USP-S | Tropical Breeze": { paint_index: 1284 },
  "USP-S | Whiteout": { paint_index: 1065 },
  "XM1014 | Ancient Lore": { paint_index: 1021 },
  "XM1014 | Banana Leaf": { paint_index: 731 },
  "XM1014 | Black Tie": { paint_index: 557 },
  "XM1014 | Blaze Orange": { paint_index: 166 },
  "XM1014 | Blue Spruce": { paint_index: 96 },
  "XM1014 | Blue Steel": { paint_index: 42 },
  "XM1014 | Blue Tire": { paint_index: 1078 },
  "XM1014 | Bone Machine": { paint_index: 370 },
  "XM1014 | CaliCamo": { paint_index: 240 },
  "XM1014 | Canvas Cloud": { paint_index: 1333 },
  "XM1014 | Charter": { paint_index: 994 },
  "XM1014 | Copperflage": { paint_index: 1287 },
  "XM1014 | Elegant Vines": { paint_index: 821 },
  "XM1014 | Entombed": { paint_index: 970 },
  "XM1014 | Fallout Warning": { paint_index: 169 },
  "XM1014 | Frost Borre": { paint_index: 760 },
  "XM1014 | Grassland": { paint_index: 95 },
  "XM1014 | Gum Wall Camo": { paint_index: 1267 },
  "XM1014 | Halftone Shift": { paint_index: 834 },
  "XM1014 | Heaven Guard": { paint_index: 314 },
  "XM1014 | Hieroglyph": { paint_index: 1254 },
  "XM1014 | Incinegator": { paint_index: 850 },
  "XM1014 | Irezumi": { paint_index: 1174 },
  "XM1014 | Jungle": { paint_index: 205 },
  "XM1014 | Mockingbird": { paint_index: 1182 },
  "XM1014 | Monster Melt": { paint_index: 146 },
  "XM1014 | Oxide Blaze": { paint_index: 706 },
  "XM1014 | Quicksilver": { paint_index: 407 },
  "XM1014 | Red Leather": { paint_index: 348 },
  "XM1014 | Red Python": { paint_index: 320 },
  "XM1014 | Run Run Run": { paint_index: 1201 },
  "XM1014 | Scumbria": { paint_index: 505 },
  "XM1014 | Seasons": { paint_index: 654 },
  "XM1014 | Slipstream": { paint_index: 616 },
  "XM1014 | Solitude": { paint_index: 1215 },
  "XM1014 | Teclu Burner": { paint_index: 521 },
  "XM1014 | Tranquility": { paint_index: 393 },
  "XM1014 | Urban Perforated": { paint_index: 135 },
  "XM1014 | VariCamo Blue": { paint_index: 238 },
  "XM1014 | Watchdog": { paint_index: 1103 },
  "XM1014 | XOXO": { paint_index: 1046 },
  "XM1014 | XoooM": { paint_index: 1381 },
  "XM1014 | Ziggy": { paint_index: 689 },
  "XM1014 | Zombie Offensive": { paint_index: 1135 },
  "★ Bayonet | Autotronic": { paint_index: 573 },
  "★ Bayonet | Black Laminate": { paint_index: 563 },
  "★ Bayonet | Blue Steel": { paint_index: 42 },
  "★ Bayonet | Boreal Forest": { paint_index: 77 },
  "★ Bayonet | Bright Water": { paint_index: 578 },
  "★ Bayonet | Case Hardened": { paint_index: 44 },
  "★ Bayonet | Crimson Web": { paint_index: 12 },
  "★ Bayonet | Damascus Steel": { paint_index: 410 },
  "★ Bayonet | Doppler": { paint_index: 417 },
  "★ Bayonet | Fade": { paint_index: 38 },
  "★ Bayonet | Forest DDPAT": { paint_index: 5 },
  "★ Bayonet | Freehand": { paint_index: 580 },
  "★ Bayonet | Gamma Doppler": { paint_index: 568 },
  "★ Bayonet | Lore": { paint_index: 558 },
  "★ Bayonet | Marble Fade": { paint_index: 413 },
  "★ Bayonet | Night": { paint_index: 40 },
  "★ Bayonet | Rust Coat": { paint_index: 414 },
  "★ Bayonet | Safari Mesh": { paint_index: 72 },
  "★ Bayonet | Scorched": { paint_index: 175 },
  "★ Bayonet | Slaughter": { paint_index: 59 },
  "★ Bayonet | Stained": { paint_index: 43 },
  "★ Bayonet | Tiger Tooth": { paint_index: 409 },
  "★ Bayonet | Ultraviolet": { paint_index: 98 },
  "★ Bayonet | Urban Masked": { paint_index: 143 },
  "★ Bloodhound Gloves | Bronzed": { paint_index: 10008 },
  "★ Bloodhound Gloves | Charred": { paint_index: 10006 },
  "★ Bloodhound Gloves | Guerrilla": { paint_index: 10039 },
  "★ Bloodhound Gloves | Snakebite": { paint_index: 10007 },
  "★ Bowie Knife | Autotronic": { paint_index: 1114 },
  "★ Bowie Knife | Black Laminate": { paint_index: 1109 },
  "★ Bowie Knife | Blue Steel": { paint_index: 42 },
  "★ Bowie Knife | Boreal Forest": { paint_index: 77 },
  "★ Bowie Knife | Bright Water": { paint_index: 579 },
  "★ Bowie Knife | Case Hardened": { paint_index: 44 },
  "★ Bowie Knife | Crimson Web": { paint_index: 12 },
  "★ Bowie Knife | Damascus Steel": { paint_index: 411 },
  "★ Bowie Knife | Doppler": { paint_index: 417 },
  "★ Bowie Knife | Fade": { paint_index: 38 },
  "★ Bowie Knife | Forest DDPAT": { paint_index: 5 },
  "★ Bowie Knife | Freehand": { paint_index: 581 },
  "★ Bowie Knife | Gamma Doppler": { paint_index: 568 },
  "★ Bowie Knife | Lore": { paint_index: 1104 },
  "★ Bowie Knife | Marble Fade": { paint_index: 413 },
  "★ Bowie Knife | Night": { paint_index: 40 },
  "★ Bowie Knife | Rust Coat": { paint_index: 414 },
  "★ Bowie Knife | Safari Mesh": { paint_index: 72 },
  "★ Bowie Knife | Scorched": { paint_index: 175 },
  "★ Bowie Knife | Slaughter": { paint_index: 59 },
  "★ Bowie Knife | Stained": { paint_index: 43 },
  "★ Bowie Knife | Tiger Tooth": { paint_index: 409 },
  "★ Bowie Knife | Ultraviolet": { paint_index: 98 },
  "★ Bowie Knife | Urban Masked": { paint_index: 143 },
  "★ Broken Fang Gloves | Jade": { paint_index: 10085 },
  "★ Broken Fang Gloves | Needle Point": { paint_index: 10087 },
  "★ Broken Fang Gloves | Unhinged": { paint_index: 10088 },
  "★ Broken Fang Gloves | Yellow-banded": { paint_index: 10086 },
  "★ Butterfly Knife | Autotronic": { paint_index: 1115 },
  "★ Butterfly Knife | Black Laminate": { paint_index: 1110 },
  "★ Butterfly Knife | Blue Steel": { paint_index: 42 },
  "★ Butterfly Knife | Boreal Forest": { paint_index: 77 },
  "★ Butterfly Knife | Bright Water": { paint_index: 579 },
  "★ Butterfly Knife | Case Hardened": { paint_index: 44 },
  "★ Butterfly Knife | Crimson Web": { paint_index: 12 },
  "★ Butterfly Knife | Damascus Steel": { paint_index: 411 },
  "★ Butterfly Knife | Doppler": { paint_index: 617 },
  "★ Butterfly Knife | Fade": { paint_index: 38 },
  "★ Butterfly Knife | Forest DDPAT": { paint_index: 5 },
  "★ Butterfly Knife | Freehand": { paint_index: 581 },
  "★ Butterfly Knife | Gamma Doppler": { paint_index: 568 },
  "★ Butterfly Knife | Lore": { paint_index: 1105 },
  "★ Butterfly Knife | Marble Fade": { paint_index: 413 },
  "★ Butterfly Knife | Night": { paint_index: 40 },
  "★ Butterfly Knife | Rust Coat": { paint_index: 414 },
  "★ Butterfly Knife | Safari Mesh": { paint_index: 72 },
  "★ Butterfly Knife | Scorched": { paint_index: 175 },
  "★ Butterfly Knife | Slaughter": { paint_index: 59 },
  "★ Butterfly Knife | Stained": { paint_index: 43 },
  "★ Butterfly Knife | Tiger Tooth": { paint_index: 409 },
  "★ Butterfly Knife | Ultraviolet": { paint_index: 98 },
  "★ Butterfly Knife | Urban Masked": { paint_index: 143 },
  "★ Classic Knife | Blue Steel": { paint_index: 42 },
  "★ Classic Knife | Boreal Forest": { paint_index: 77 },
  "★ Classic Knife | Case Hardened": { paint_index: 44 },
  "★ Classic Knife | Crimson Web": { paint_index: 12 },
  "★ Classic Knife | Fade": { paint_index: 38 },
  "★ Classic Knife | Forest DDPAT": { paint_index: 5 },
  "★ Classic Knife | Night Stripe": { paint_index: 735 },
  "★ Classic Knife | Safari Mesh": { paint_index: 72 },
  "★ Classic Knife | Scorched": { paint_index: 175 },
  "★ Classic Knife | Slaughter": { paint_index: 59 },
  "★ Classic Knife | Stained": { paint_index: 43 },
  "★ Classic Knife | Urban Masked": { paint_index: 143 },
  "★ Driver Gloves | Black Tie": { paint_index: 10072 },
  "★ Driver Gloves | Brocade Crane": { paint_index: 1399 },
  "★ Driver Gloves | Brocade Flowers": { paint_index: 1400 },
  "★ Driver Gloves | Convoy": { paint_index: 10015 },
  "★ Driver Gloves | Crimson Weave": { paint_index: 10016 },
  "★ Driver Gloves | Diamondback": { paint_index: 10040 },
  "★ Driver Gloves | Dragon Fists": { paint_index: 1401 },
  "★ Driver Gloves | Garden": { paint_index: 1402 },
  "★ Driver Gloves | Hand Sweaters": { paint_index: 1439 },
  "★ Driver Gloves | Imperial Plaid": { paint_index: 10042 },
  "★ Driver Gloves | King Snake": { paint_index: 10041 },
  "★ Driver Gloves | Lunar Weave": { paint_index: 10013 },
  "★ Driver Gloves | Overtake": { paint_index: 10043 },
  "★ Driver Gloves | Plum Quill": { paint_index: 1412 },
  "★ Driver Gloves | Queen Jaguar": { paint_index: 10071 },
  "★ Driver Gloves | Racing Green": { paint_index: 10044 },
  "★ Driver Gloves | Rezan the Red": { paint_index: 10069 },
  "★ Driver Gloves | Seigaiha": { paint_index: 1404 },
  "★ Driver Gloves | Snow Leopard": { paint_index: 10070 },
  "★ Driver Gloves | Wave Chaser": { paint_index: 1398 },
  "★ Falchion Knife | Autotronic": { paint_index: 1116 },
  "★ Falchion Knife | Black Laminate": { paint_index: 1111 },
  "★ Falchion Knife | Blue Steel": { paint_index: 42 },
  "★ Falchion Knife | Boreal Forest": { paint_index: 77 },
  "★ Falchion Knife | Bright Water": { paint_index: 579 },
  "★ Falchion Knife | Case Hardened": { paint_index: 44 },
  "★ Falchion Knife | Crimson Web": { paint_index: 12 },
  "★ Falchion Knife | Damascus Steel": { paint_index: 411 },
  "★ Falchion Knife | Doppler": { paint_index: 417 },
  "★ Falchion Knife | Fade": { paint_index: 38 },
  "★ Falchion Knife | Forest DDPAT": { paint_index: 5 },
  "★ Falchion Knife | Freehand": { paint_index: 581 },
  "★ Falchion Knife | Gamma Doppler": { paint_index: 568 },
  "★ Falchion Knife | Lore": { paint_index: 1106 },
  "★ Falchion Knife | Marble Fade": { paint_index: 413 },
  "★ Falchion Knife | Night": { paint_index: 40 },
  "★ Falchion Knife | Rust Coat": { paint_index: 414 },
  "★ Falchion Knife | Safari Mesh": { paint_index: 72 },
  "★ Falchion Knife | Scorched": { paint_index: 175 },
  "★ Falchion Knife | Slaughter": { paint_index: 59 },
  "★ Falchion Knife | Stained": { paint_index: 43 },
  "★ Falchion Knife | Tiger Tooth": { paint_index: 409 },
  "★ Falchion Knife | Ultraviolet": { paint_index: 621 },
  "★ Falchion Knife | Urban Masked": { paint_index: 143 },
  "★ Flip Knife | Autotronic": { paint_index: 574 },
  "★ Flip Knife | Black Laminate": { paint_index: 564 },
  "★ Flip Knife | Blue Steel": { paint_index: 42 },
  "★ Flip Knife | Boreal Forest": { paint_index: 77 },
  "★ Flip Knife | Bright Water": { paint_index: 578 },
  "★ Flip Knife | Case Hardened": { paint_index: 44 },
  "★ Flip Knife | Crimson Web": { paint_index: 12 },
  "★ Flip Knife | Damascus Steel": { paint_index: 410 },
  "★ Flip Knife | Doppler": { paint_index: 417 },
  "★ Flip Knife | Fade": { paint_index: 38 },
  "★ Flip Knife | Forest DDPAT": { paint_index: 5 },
  "★ Flip Knife | Freehand": { paint_index: 580 },
  "★ Flip Knife | Gamma Doppler": { paint_index: 568 },
  "★ Flip Knife | Lore": { paint_index: 559 },
  "★ Flip Knife | Marble Fade": { paint_index: 413 },
  "★ Flip Knife | Night": { paint_index: 40 },
  "★ Flip Knife | Rust Coat": { paint_index: 414 },
  "★ Flip Knife | Safari Mesh": { paint_index: 72 },
  "★ Flip Knife | Scorched": { paint_index: 175 },
  "★ Flip Knife | Slaughter": { paint_index: 59 },
  "★ Flip Knife | Stained": { paint_index: 43 },
  "★ Flip Knife | Tiger Tooth": { paint_index: 409 },
  "★ Flip Knife | Ultraviolet": { paint_index: 98 },
  "★ Flip Knife | Urban Masked": { paint_index: 143 },
  "★ Gut Knife | Autotronic": { paint_index: 575 },
  "★ Gut Knife | Black Laminate": { paint_index: 565 },
  "★ Gut Knife | Blue Steel": { paint_index: 42 },
  "★ Gut Knife | Boreal Forest": { paint_index: 77 },
  "★ Gut Knife | Bright Water": { paint_index: 578 },
  "★ Gut Knife | Case Hardened": { paint_index: 44 },
  "★ Gut Knife | Crimson Web": { paint_index: 12 },
  "★ Gut Knife | Damascus Steel": { paint_index: 410 },
  "★ Gut Knife | Doppler": { paint_index: 417 },
  "★ Gut Knife | Fade": { paint_index: 38 },
  "★ Gut Knife | Forest DDPAT": { paint_index: 5 },
  "★ Gut Knife | Freehand": { paint_index: 580 },
  "★ Gut Knife | Gamma Doppler": { paint_index: 568 },
  "★ Gut Knife | Lore": { paint_index: 560 },
  "★ Gut Knife | Marble Fade": { paint_index: 413 },
  "★ Gut Knife | Night": { paint_index: 40 },
  "★ Gut Knife | Rust Coat": { paint_index: 414 },
  "★ Gut Knife | Safari Mesh": { paint_index: 72 },
  "★ Gut Knife | Scorched": { paint_index: 175 },
  "★ Gut Knife | Slaughter": { paint_index: 59 },
  "★ Gut Knife | Stained": { paint_index: 43 },
  "★ Gut Knife | Tiger Tooth": { paint_index: 409 },
  "★ Gut Knife | Ultraviolet": { paint_index: 98 },
  "★ Gut Knife | Urban Masked": { paint_index: 143 },
  "★ Hand Wraps | Arboreal": { paint_index: 10056 },
  "★ Hand Wraps | Badlands": { paint_index: 10036 },
  "★ Hand Wraps | CAUTION!": { paint_index: 10084 },
  "★ Hand Wraps | Cobalt Skulls": { paint_index: 10053 },
  "★ Hand Wraps | Constrictor": { paint_index: 10083 },
  "★ Hand Wraps | Desert Shamagh": { paint_index: 10081 },
  "★ Hand Wraps | Duct Tape": { paint_index: 10055 },
  "★ Hand Wraps | Giraffe": { paint_index: 10082 },
  "★ Hand Wraps | Leather": { paint_index: 10009 },
  "★ Hand Wraps | Overprint": { paint_index: 10054 },
  "★ Hand Wraps | Slaughter": { paint_index: 10021 },
  "★ Hand Wraps | Spruce DDPAT": { paint_index: 10010 },
  "★ Huntsman Knife | Autotronic": { paint_index: 1117 },
  "★ Huntsman Knife | Black Laminate": { paint_index: 1112 },
  "★ Huntsman Knife | Blue Steel": { paint_index: 42 },
  "★ Huntsman Knife | Boreal Forest": { paint_index: 77 },
  "★ Huntsman Knife | Bright Water": { paint_index: 579 },
  "★ Huntsman Knife | Case Hardened": { paint_index: 44 },
  "★ Huntsman Knife | Crimson Web": { paint_index: 12 },
  "★ Huntsman Knife | Damascus Steel": { paint_index: 411 },
  "★ Huntsman Knife | Doppler": { paint_index: 417 },
  "★ Huntsman Knife | Fade": { paint_index: 38 },
  "★ Huntsman Knife | Forest DDPAT": { paint_index: 5 },
  "★ Huntsman Knife | Freehand": { paint_index: 581 },
  "★ Huntsman Knife | Gamma Doppler": { paint_index: 568 },
  "★ Huntsman Knife | Lore": { paint_index: 1107 },
  "★ Huntsman Knife | Marble Fade": { paint_index: 413 },
  "★ Huntsman Knife | Night": { paint_index: 40 },
  "★ Huntsman Knife | Rust Coat": { paint_index: 414 },
  "★ Huntsman Knife | Safari Mesh": { paint_index: 72 },
  "★ Huntsman Knife | Scorched": { paint_index: 175 },
  "★ Huntsman Knife | Slaughter": { paint_index: 59 },
  "★ Huntsman Knife | Stained": { paint_index: 43 },
  "★ Huntsman Knife | Tiger Tooth": { paint_index: 409 },
  "★ Huntsman Knife | Ultraviolet": { paint_index: 620 },
  "★ Huntsman Knife | Urban Masked": { paint_index: 143 },
  "★ Hydra Gloves | Case Hardened": { paint_index: 10060 },
  "★ Hydra Gloves | Emerald": { paint_index: 10057 },
  "★ Hydra Gloves | Mangrove": { paint_index: 10058 },
  "★ Hydra Gloves | Rattler": { paint_index: 10059 },
  "★ Karambit | Autotronic": { paint_index: 576 },
  "★ Karambit | Black Laminate": { paint_index: 566 },
  "★ Karambit | Blue Steel": { paint_index: 42 },
  "★ Karambit | Boreal Forest": { paint_index: 77 },
  "★ Karambit | Bright Water": { paint_index: 578 },
  "★ Karambit | Case Hardened": { paint_index: 44 },
  "★ Karambit | Crimson Web": { paint_index: 12 },
  "★ Karambit | Damascus Steel": { paint_index: 410 },
  "★ Karambit | Doppler": { paint_index: 417 },
  "★ Karambit | Fade": { paint_index: 38 },
  "★ Karambit | Forest DDPAT": { paint_index: 5 },
  "★ Karambit | Freehand": { paint_index: 582 },
  "★ Karambit | Gamma Doppler": { paint_index: 568 },
  "★ Karambit | Lore": { paint_index: 561 },
  "★ Karambit | Marble Fade": { paint_index: 413 },
  "★ Karambit | Night": { paint_index: 40 },
  "★ Karambit | Rust Coat": { paint_index: 414 },
  "★ Karambit | Safari Mesh": { paint_index: 72 },
  "★ Karambit | Scorched": { paint_index: 175 },
  "★ Karambit | Slaughter": { paint_index: 59 },
  "★ Karambit | Stained": { paint_index: 43 },
  "★ Karambit | Tiger Tooth": { paint_index: 409 },
  "★ Karambit | Ultraviolet": { paint_index: 98 },
  "★ Karambit | Urban Masked": { paint_index: 143 },
  "★ Kukri Knife | Blue Steel": { paint_index: 42 },
  "★ Kukri Knife | Boreal Forest": { paint_index: 77 },
  "★ Kukri Knife | Case Hardened": { paint_index: 44 },
  "★ Kukri Knife | Crimson Web": { paint_index: 12 },
  "★ Kukri Knife | Fade": { paint_index: 38 },
  "★ Kukri Knife | Forest DDPAT": { paint_index: 5 },
  "★ Kukri Knife | Night Stripe": { paint_index: 735 },
  "★ Kukri Knife | Safari Mesh": { paint_index: 72 },
  "★ Kukri Knife | Scorched": { paint_index: 175 },
  "★ Kukri Knife | Slaughter": { paint_index: 59 },
  "★ Kukri Knife | Stained": { paint_index: 43 },
  "★ Kukri Knife | Urban Masked": { paint_index: 143 },
  "★ M9 Bayonet | Autotronic": { paint_index: 577 },
  "★ M9 Bayonet | Black Laminate": { paint_index: 567 },
  "★ M9 Bayonet | Blue Steel": { paint_index: 42 },
  "★ M9 Bayonet | Boreal Forest": { paint_index: 77 },
  "★ M9 Bayonet | Bright Water": { paint_index: 579 },
  "★ M9 Bayonet | Case Hardened": { paint_index: 44 },
  "★ M9 Bayonet | Crimson Web": { paint_index: 12 },
  "★ M9 Bayonet | Damascus Steel": { paint_index: 411 },
  "★ M9 Bayonet | Doppler": { paint_index: 417 },
  "★ M9 Bayonet | Fade": { paint_index: 38 },
  "★ M9 Bayonet | Forest DDPAT": { paint_index: 5 },
  "★ M9 Bayonet | Freehand": { paint_index: 581 },
  "★ M9 Bayonet | Gamma Doppler": { paint_index: 568 },
  "★ M9 Bayonet | Lore": { paint_index: 562 },
  "★ M9 Bayonet | Marble Fade": { paint_index: 413 },
  "★ M9 Bayonet | Night": { paint_index: 40 },
  "★ M9 Bayonet | Rust Coat": { paint_index: 414 },
  "★ M9 Bayonet | Safari Mesh": { paint_index: 72 },
  "★ M9 Bayonet | Scorched": { paint_index: 175 },
  "★ M9 Bayonet | Slaughter": { paint_index: 59 },
  "★ M9 Bayonet | Stained": { paint_index: 43 },
  "★ M9 Bayonet | Tiger Tooth": { paint_index: 409 },
  "★ M9 Bayonet | Ultraviolet": { paint_index: 98 },
  "★ M9 Bayonet | Urban Masked": { paint_index: 143 },
  "★ Moto Gloves | 3rd Commando Company": { paint_index: 10080 },
  "★ Moto Gloves | Blood Pressure": { paint_index: 10079 },
  "★ Moto Gloves | Boom!": { paint_index: 10027 },
  "★ Moto Gloves | Cool Mint": { paint_index: 10028 },
  "★ Moto Gloves | Eclipse": { paint_index: 10024 },
  "★ Moto Gloves | Finish Line": { paint_index: 10077 },
  "★ Moto Gloves | POW!": { paint_index: 10049 },
  "★ Moto Gloves | Polygon": { paint_index: 10052 },
  "★ Moto Gloves | Smoke Out": { paint_index: 10078 },
  "★ Moto Gloves | Spearmint": { paint_index: 10026 },
  "★ Moto Gloves | Transport": { paint_index: 10051 },
  "★ Moto Gloves | Turtle": { paint_index: 10050 },
  "★ Navaja Knife | Blue Steel": { paint_index: 42 },
  "★ Navaja Knife | Boreal Forest": { paint_index: 77 },
  "★ Navaja Knife | Case Hardened": { paint_index: 44 },
  "★ Navaja Knife | Crimson Web": { paint_index: 12 },
  "★ Navaja Knife | Damascus Steel": { paint_index: 857 },
  "★ Navaja Knife | Doppler": { paint_index: 417 },
  "★ Navaja Knife | Fade": { paint_index: 38 },
  "★ Navaja Knife | Forest DDPAT": { paint_index: 5 },
  "★ Navaja Knife | Marble Fade": { paint_index: 413 },
  "★ Navaja Knife | Night Stripe": { paint_index: 735 },
  "★ Navaja Knife | Rust Coat": { paint_index: 414 },
  "★ Navaja Knife | Safari Mesh": { paint_index: 72 },
  "★ Navaja Knife | Scorched": { paint_index: 175 },
  "★ Navaja Knife | Slaughter": { paint_index: 59 },
  "★ Navaja Knife | Stained": { paint_index: 43 },
  "★ Navaja Knife | Tiger Tooth": { paint_index: 409 },
  "★ Navaja Knife | Ultraviolet": { paint_index: 98 },
  "★ Navaja Knife | Urban Masked": { paint_index: 143 },
  "★ Nomad Knife | Blue Steel": { paint_index: 42 },
  "★ Nomad Knife | Boreal Forest": { paint_index: 77 },
  "★ Nomad Knife | Case Hardened": { paint_index: 44 },
  "★ Nomad Knife | Crimson Web": { paint_index: 12 },
  "★ Nomad Knife | Damascus Steel": { paint_index: 410 },
  "★ Nomad Knife | Doppler": { paint_index: 417 },
  "★ Nomad Knife | Fade": { paint_index: 38 },
  "★ Nomad Knife | Forest DDPAT": { paint_index: 5 },
  "★ Nomad Knife | Marble Fade": { paint_index: 413 },
  "★ Nomad Knife | Night Stripe": { paint_index: 735 },
  "★ Nomad Knife | Rust Coat": { paint_index: 414 },
  "★ Nomad Knife | Safari Mesh": { paint_index: 72 },
  "★ Nomad Knife | Scorched": { paint_index: 175 },
  "★ Nomad Knife | Slaughter": { paint_index: 59 },
  "★ Nomad Knife | Stained": { paint_index: 43 },
  "★ Nomad Knife | Tiger Tooth": { paint_index: 409 },
  "★ Nomad Knife | Ultraviolet": { paint_index: 98 },
  "★ Nomad Knife | Urban Masked": { paint_index: 143 },
  "★ Paracord Knife | Blue Steel": { paint_index: 42 },
  "★ Paracord Knife | Boreal Forest": { paint_index: 77 },
  "★ Paracord Knife | Case Hardened": { paint_index: 44 },
  "★ Paracord Knife | Crimson Web": { paint_index: 12 },
  "★ Paracord Knife | Damascus Steel": { paint_index: 410 },
  "★ Paracord Knife | Doppler": { paint_index: 417 },
  "★ Paracord Knife | Fade": { paint_index: 38 },
  "★ Paracord Knife | Forest DDPAT": { paint_index: 5 },
  "★ Paracord Knife | Marble Fade": { paint_index: 413 },
  "★ Paracord Knife | Night Stripe": { paint_index: 735 },
  "★ Paracord Knife | Rust Coat": { paint_index: 414 },
  "★ Paracord Knife | Safari Mesh": { paint_index: 72 },
  "★ Paracord Knife | Scorched": { paint_index: 175 },
  "★ Paracord Knife | Slaughter": { paint_index: 59 },
  "★ Paracord Knife | Stained": { paint_index: 43 },
  "★ Paracord Knife | Tiger Tooth": { paint_index: 409 },
  "★ Paracord Knife | Ultraviolet": { paint_index: 621 },
  "★ Paracord Knife | Urban Masked": { paint_index: 143 },
  "★ Shadow Daggers | Autotronic": { paint_index: 1118 },
  "★ Shadow Daggers | Black Laminate": { paint_index: 1113 },
  "★ Shadow Daggers | Blue Steel": { paint_index: 42 },
  "★ Shadow Daggers | Boreal Forest": { paint_index: 77 },
  "★ Shadow Daggers | Bright Water": { paint_index: 579 },
  "★ Shadow Daggers | Case Hardened": { paint_index: 44 },
  "★ Shadow Daggers | Crimson Web": { paint_index: 12 },
  "★ Shadow Daggers | Damascus Steel": { paint_index: 411 },
  "★ Shadow Daggers | Doppler": { paint_index: 617 },
  "★ Shadow Daggers | Fade": { paint_index: 38 },
  "★ Shadow Daggers | Forest DDPAT": { paint_index: 5 },
  "★ Shadow Daggers | Freehand": { paint_index: 581 },
  "★ Shadow Daggers | Gamma Doppler": { paint_index: 568 },
  "★ Shadow Daggers | Lore": { paint_index: 1108 },
  "★ Shadow Daggers | Marble Fade": { paint_index: 413 },
  "★ Shadow Daggers | Night": { paint_index: 40 },
  "★ Shadow Daggers | Rust Coat": { paint_index: 414 },
  "★ Shadow Daggers | Safari Mesh": { paint_index: 72 },
  "★ Shadow Daggers | Scorched": { paint_index: 175 },
  "★ Shadow Daggers | Slaughter": { paint_index: 59 },
  "★ Shadow Daggers | Stained": { paint_index: 43 },
  "★ Shadow Daggers | Tiger Tooth": { paint_index: 409 },
  "★ Shadow Daggers | Ultraviolet": { paint_index: 98 },
  "★ Shadow Daggers | Urban Masked": { paint_index: 143 },
  "★ Skeleton Knife | Blue Steel": { paint_index: 42 },
  "★ Skeleton Knife | Boreal Forest": { paint_index: 77 },
  "★ Skeleton Knife | Case Hardened": { paint_index: 44 },
  "★ Skeleton Knife | Crimson Web": { paint_index: 12 },
  "★ Skeleton Knife | Damascus Steel": { paint_index: 410 },
  "★ Skeleton Knife | Doppler": { paint_index: 417 },
  "★ Skeleton Knife | Fade": { paint_index: 38 },
  "★ Skeleton Knife | Forest DDPAT": { paint_index: 5 },
  "★ Skeleton Knife | Marble Fade": { paint_index: 413 },
  "★ Skeleton Knife | Night Stripe": { paint_index: 735 },
  "★ Skeleton Knife | Rust Coat": { paint_index: 414 },
  "★ Skeleton Knife | Safari Mesh": { paint_index: 72 },
  "★ Skeleton Knife | Scorched": { paint_index: 175 },
  "★ Skeleton Knife | Slaughter": { paint_index: 59 },
  "★ Skeleton Knife | Stained": { paint_index: 43 },
  "★ Skeleton Knife | Tiger Tooth": { paint_index: 409 },
  "★ Skeleton Knife | Ultraviolet": { paint_index: 98 },
  "★ Skeleton Knife | Urban Masked": { paint_index: 143 },
  "★ Specialist Gloves | Big Swell": { paint_index: 1437 },
  "★ Specialist Gloves | Blackbook": { paint_index: 1414 },
  "★ Specialist Gloves | Buckshot": { paint_index: 10062 },
  "★ Specialist Gloves | Chocolate Chesterfield": { paint_index: 1415 },
  "★ Specialist Gloves | Cloud Chaser": { paint_index: 1440 },
  "★ Specialist Gloves | Crimson Kimono": { paint_index: 10033 },
  "★ Specialist Gloves | Crimson Web": { paint_index: 10061 },
  "★ Specialist Gloves | Emerald Web": { paint_index: 10034 },
  "★ Specialist Gloves | Fade": { paint_index: 10063 },
  "★ Specialist Gloves | Field Agent": { paint_index: 10068 },
  "★ Specialist Gloves | Forest DDPAT": { paint_index: 10030 },
  "★ Specialist Gloves | Foundation": { paint_index: 10035 },
  "★ Specialist Gloves | Lime Polycam": { paint_index: 1413 },
  "★ Specialist Gloves | Lt. Commander": { paint_index: 10066 },
  "★ Specialist Gloves | Marble Fade": { paint_index: 10065 },
  "★ Specialist Gloves | Mogul": { paint_index: 10064 },
  "★ Specialist Gloves | Pillow Punchers": { paint_index: 1438 },
  "★ Specialist Gloves | Sunburst": { paint_index: 1416 },
  "★ Specialist Gloves | Tiger Strike": { paint_index: 10067 },
  "★ Sport Gloves | Amphibious": { paint_index: 10045 },
  "★ Sport Gloves | Arid": { paint_index: 10019 },
  "★ Sport Gloves | Big Game": { paint_index: 10074 },
  "★ Sport Gloves | Blaze": { paint_index: 1407 },
  "★ Sport Gloves | Bronze Morph": { paint_index: 10046 },
  "★ Sport Gloves | Creme Pinstripe": { paint_index: 1408 },
  "★ Sport Gloves | Frosty": { paint_index: 1406 },
  "★ Sport Gloves | Hedge Maze": { paint_index: 10038 },
  "★ Sport Gloves | Nocts": { paint_index: 10076 },
  "★ Sport Gloves | Occult": { paint_index: 1417 },
  "★ Sport Gloves | Omega": { paint_index: 10047 },
  "★ Sport Gloves | Pandora's Box": { paint_index: 10037 },
  "★ Sport Gloves | Red Racer": { paint_index: 1409 },
  "★ Sport Gloves | Scarlet Shamagh": { paint_index: 10075 },
  "★ Sport Gloves | Slingshot": { paint_index: 10073 },
  "★ Sport Gloves | Superconductor": { paint_index: 10018 },
  "★ Sport Gloves | Ultra Violent": { paint_index: 1410 },
  "★ Sport Gloves | Vice": { paint_index: 10048 },
  "★ Sport Gloves | Violet Beadwork": { paint_index: 1405 },
  "★ Stiletto Knife | Blue Steel": { paint_index: 42 },
  "★ Stiletto Knife | Boreal Forest": { paint_index: 77 },
  "★ Stiletto Knife | Case Hardened": { paint_index: 44 },
  "★ Stiletto Knife | Crimson Web": { paint_index: 12 },
  "★ Stiletto Knife | Damascus Steel": { paint_index: 857 },
  "★ Stiletto Knife | Doppler": { paint_index: 417 },
  "★ Stiletto Knife | Fade": { paint_index: 38 },
  "★ Stiletto Knife | Forest DDPAT": { paint_index: 5 },
  "★ Stiletto Knife | Marble Fade": { paint_index: 413 },
  "★ Stiletto Knife | Night Stripe": { paint_index: 735 },
  "★ Stiletto Knife | Rust Coat": { paint_index: 414 },
  "★ Stiletto Knife | Safari Mesh": { paint_index: 72 },
  "★ Stiletto Knife | Scorched": { paint_index: 175 },
  "★ Stiletto Knife | Slaughter": { paint_index: 59 },
  "★ Stiletto Knife | Stained": { paint_index: 43 },
  "★ Stiletto Knife | Tiger Tooth": { paint_index: 409 },
  "★ Stiletto Knife | Ultraviolet": { paint_index: 98 },
  "★ Stiletto Knife | Urban Masked": { paint_index: 143 },
  "★ Survival Knife | Blue Steel": { paint_index: 42 },
  "★ Survival Knife | Boreal Forest": { paint_index: 77 },
  "★ Survival Knife | Case Hardened": { paint_index: 44 },
  "★ Survival Knife | Crimson Web": { paint_index: 12 },
  "★ Survival Knife | Damascus Steel": { paint_index: 410 },
  "★ Survival Knife | Doppler": { paint_index: 417 },
  "★ Survival Knife | Fade": { paint_index: 38 },
  "★ Survival Knife | Forest DDPAT": { paint_index: 5 },
  "★ Survival Knife | Marble Fade": { paint_index: 413 },
  "★ Survival Knife | Night Stripe": { paint_index: 735 },
  "★ Survival Knife | Rust Coat": { paint_index: 414 },
  "★ Survival Knife | Safari Mesh": { paint_index: 72 },
  "★ Survival Knife | Scorched": { paint_index: 175 },
  "★ Survival Knife | Slaughter": { paint_index: 59 },
  "★ Survival Knife | Stained": { paint_index: 43 },
  "★ Survival Knife | Tiger Tooth": { paint_index: 409 },
  "★ Survival Knife | Ultraviolet": { paint_index: 98 },
  "★ Survival Knife | Urban Masked": { paint_index: 143 },
  "★ Talon Knife | Blue Steel": { paint_index: 42 },
  "★ Talon Knife | Boreal Forest": { paint_index: 77 },
  "★ Talon Knife | Case Hardened": { paint_index: 44 },
  "★ Talon Knife | Crimson Web": { paint_index: 12 },
  "★ Talon Knife | Damascus Steel": { paint_index: 858 },
  "★ Talon Knife | Doppler": { paint_index: 417 },
  "★ Talon Knife | Fade": { paint_index: 38 },
  "★ Talon Knife | Forest DDPAT": { paint_index: 5 },
  "★ Talon Knife | Marble Fade": { paint_index: 856 },
  "★ Talon Knife | Night Stripe": { paint_index: 735 },
  "★ Talon Knife | Rust Coat": { paint_index: 414 },
  "★ Talon Knife | Safari Mesh": { paint_index: 72 },
  "★ Talon Knife | Scorched": { paint_index: 175 },
  "★ Talon Knife | Slaughter": { paint_index: 59 },
  "★ Talon Knife | Stained": { paint_index: 43 },
  "★ Talon Knife | Tiger Tooth": { paint_index: 409 },
  "★ Talon Knife | Ultraviolet": { paint_index: 98 },
  "★ Talon Knife | Urban Masked": { paint_index: 143 },
  "★ Ursus Knife | Blue Steel": { paint_index: 42 },
  "★ Ursus Knife | Boreal Forest": { paint_index: 77 },
  "★ Ursus Knife | Case Hardened": { paint_index: 44 },
  "★ Ursus Knife | Crimson Web": { paint_index: 12 },
  "★ Ursus Knife | Damascus Steel": { paint_index: 857 },
  "★ Ursus Knife | Doppler": { paint_index: 417 },
  "★ Ursus Knife | Fade": { paint_index: 38 },
  "★ Ursus Knife | Forest DDPAT": { paint_index: 5 },
  "★ Ursus Knife | Marble Fade": { paint_index: 413 },
  "★ Ursus Knife | Night Stripe": { paint_index: 735 },
  "★ Ursus Knife | Rust Coat": { paint_index: 414 },
  "★ Ursus Knife | Safari Mesh": { paint_index: 72 },
  "★ Ursus Knife | Scorched": { paint_index: 175 },
  "★ Ursus Knife | Slaughter": { paint_index: 59 },
  "★ Ursus Knife | Stained": { paint_index: 43 },
  "★ Ursus Knife | Tiger Tooth": { paint_index: 409 },
  "★ Ursus Knife | Ultraviolet": { paint_index: 98 },
  "★ Ursus Knife | Urban Masked": { paint_index: 143 },
};

export const getPaintIndex = (skinName: string): number | null => {
  // Remove wear and StatTrak/Souvenir prefix
  let cleanName = skinName
    .replace(/\(.*?\)$/, "")
    .replace("StatTrak™ ", "")
    .replace("Souvenir ", "")
    .trim();

  return skinDatabase[cleanName]?.paint_index || null;
};

export const getBuffId = (skinName: string): number | null => {
  // Remove wear and StatTrak/Souvenir prefix
  let cleanName = skinName
    .replace(/\(.*?\)$/, "")
    .replace("StatTrak™ ", "")
    .replace("Souvenir ", "")
    .trim();

  return skinDatabase[cleanName]?.buff_id || null;
};
